"""Generated-content footer wording authority."""

from __future__ import annotations

from scripts.architecture_linter.facts import FactsProvider
from scripts.architecture_linter.groups.common import checked_facts, violation
from scripts.architecture_linter.models import Violation

_OWNER = "src/apm_cli/compilation/footer.py"
_CONSUMERS = (
    "src/apm_cli/compilation/agents_compiler.py",
    "src/apm_cli/compilation/claude_formatter.py",
    "src/apm_cli/compilation/distributed_compiler.py",
    "src/apm_cli/compilation/template_builder.py",
)
_COMPILATION_PREFIX = "src/apm_cli/compilation/"
_FUNCTION = "build_generation_footer"
_OWNERSHIP_WORDING = "was generated by APM CLI. Do not edit manually."


def check_generation_footer_authority(
    provider: FactsProvider,
    rule_id: str,
) -> tuple[Violation, ...]:
    """Require all generated footer wording to route through its owner."""
    findings: list[Violation] = []
    owner, failures = checked_facts(provider, _OWNER, rule_id, require_python=True)
    findings.extend(failures)
    if owner is not None:
        definitions = tuple(
            definition
            for definition in owner.definitions
            if definition.name == _FUNCTION
            and definition.kind == "function"
            and definition.scope == "<module>"
        )
        if len(definitions) != 1:
            findings.append(
                violation(
                    rule_id,
                    _OWNER,
                    f"{_FUNCTION} must have exactly one module-level definition",
                    line=1,
                )
            )

    for path in _CONSUMERS:
        facts, failures = checked_facts(provider, path, rule_id, require_python=True)
        findings.extend(failures)
        if facts is not None and not any(call.qualname == _FUNCTION for call in facts.calls):
            findings.append(
                violation(
                    rule_id,
                    path,
                    f"generated footer must use {_FUNCTION}",
                    line=1,
                )
            )

    for path in provider.inventory:
        if path == _OWNER or not path.startswith(_COMPILATION_PREFIX) or not path.endswith(".py"):
            continue
        facts, failures = checked_facts(provider, path, rule_id, require_python=True)
        findings.extend(failures)
        if facts is None:
            continue
        for literal in facts.literals:
            if _OWNERSHIP_WORDING in literal.value_repr:
                findings.append(
                    violation(
                        rule_id,
                        path,
                        f"footer ownership wording duplicates {_OWNER}",
                        line=literal.line,
                        column=literal.column + 1,
                    )
                )
    return tuple(findings)


__all__ = ["check_generation_footer_authority"]
