# pylint: disable=duplicate-code
"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ...core.target_detection import (
    CompileTargetType,
)
from ...primitives.models import PrimitiveCollection
from ...utils.paths import portable_relpath
from ..constants import BUILD_ID_PLACEHOLDER
from ..link_resolver import validate_link_targets
from ..template_builder import (
    TemplateData,
)

_logger = logging.getLogger(__name__)


# User-facing target aliases that map to the canonical "vscode" target.
# Kept in sync with target_detection.detect_target().
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "windsurf",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"

# Compiler families allowed inside a multi-target frozenset (built by
# _resolve_compile_target() from CLI-validated target names). Kept narrow
# because the frozenset path bypasses _KNOWN_TARGETS validation.
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


def _apply_single_file_mode(config: CompilationConfig, compilation_config: dict) -> None:
    """Set single-file strategy when the single_file flag is truthy."""
    if compilation_config.get("single_file"):
        config.strategy = "single-file"
        config.single_agents = True


def _apply_exclude_config(config: CompilationConfig, compilation_config: dict) -> None:
    """Apply the exclude patterns from compilation_config into config."""
    exclude_patterns = compilation_config.get("exclude")
    if isinstance(exclude_patterns, list):
        config.exclude = exclude_patterns
    elif isinstance(exclude_patterns, str):
        config.exclude = [exclude_patterns]


def _apply_apm_yml_compilation_config(config: CompilationConfig, compilation_config: dict) -> None:
    """Apply compilation settings from apm.yml compilation_config dict into config (mutates)."""
    if "output" in compilation_config:
        config.output_path = compilation_config["output"]
    if "chatmode" in compilation_config:
        config.chatmode = compilation_config["chatmode"]
    if "resolve_links" in compilation_config:
        config.resolve_links = compilation_config["resolve_links"]
    if "target" in compilation_config:
        config.target = compilation_config["target"]
    if "strategy" in compilation_config:
        config.strategy = compilation_config["strategy"]
    _apply_single_file_mode(config, compilation_config)
    placement_config = compilation_config.get("placement", {})
    if "min_instructions_per_file" in placement_config:
        config.min_instructions_per_file = placement_config["min_instructions_per_file"]
    if "source_attribution" in compilation_config:
        config.source_attribution = compilation_config["source_attribution"]
    _apply_exclude_config(config, compilation_config)


@dataclass
class CompilationConfig:
    """Configuration for AGENTS.md compilation."""

    output_path: str = "AGENTS.md"
    chatmode: str | None = None
    resolve_links: bool = True
    dry_run: bool = False
    with_constitution: bool = True  # Phase 0 feature flag

    # Multi-target compilation settings
    # "vscode" or "agents" -> AGENTS.md + .github/
    # "claude" -> CLAUDE.md + .claude/
    # "all" -> both targets
    # frozenset({"agents","claude"}) -> AGENTS.md + CLAUDE.md (multi-target)
    target: CompileTargetType = "all"

    # Distributed compilation settings (Task 7)
    strategy: str = "distributed"  # "distributed" or "single-file"
    single_agents: bool = False  # Force single-file mode
    trace: bool = False  # Show source attribution and conflicts
    local_only: bool = False  # Ignore dependencies, compile only local primitives
    debug: bool = False  # Show context optimizer analysis and metrics
    min_instructions_per_file: int = (
        1  # Minimum instructions per AGENTS.md file (Minimal Context Principle)
    )
    source_attribution: bool = True  # Include source file comments
    clean_orphaned: bool = False  # Remove orphaned AGENTS.md files
    exclude: list[str] = None  # Glob patterns for directories to exclude during compilation

    def __post_init__(self):
        """Handle CLI flag precedence after initialization."""
        if self.single_agents:
            self.strategy = "single-file"
        # Initialize exclude list if None
        if self.exclude is None:
            self.exclude = []

    @classmethod
    def from_apm_yml(cls, **overrides) -> CompilationConfig:
        """Create configuration from apm.yml with command-line overrides.

        Args:
            **overrides: Command-line arguments that override config file values.

        Returns:
            CompilationConfig: Configuration with apm.yml values and overrides applied.
        """
        config = cls()

        # Try to load from apm.yml
        try:
            from pathlib import Path

            if Path("apm.yml").exists():
                from ...utils.yaml_io import load_yaml

                apm_config = load_yaml("apm.yml") or {}

                # Look for compilation section
                compilation_config = apm_config.get("compilation", {})

                # Apply config file values
                _apply_apm_yml_compilation_config(config, compilation_config)

        except Exception as exc:
            _logger.debug("Config loading failed, using defaults: %s", exc)

        # Apply command-line overrides (highest priority)
        for key, value in overrides.items():
            if value is not None:  # Only override if explicitly provided
                setattr(config, key, value)

        # Handle CLI flag precedence
        if config.single_agents:
            config.strategy = "single-file"

        return config


@dataclass
class CompilationResult:
    """Result of AGENTS.md compilation."""

    success: bool
    output_path: str
    content: str
    warnings: list[str]
    errors: list[str]
    stats: dict[str, Any]
    has_critical_security: bool = False


class AgentsCompiler:
    """Main compiler for generating AGENTS.md files."""

    def __init__(self, base_dir: str = "."):
        """Initialize the compiler.

        Args:
            base_dir (str): Base directory for compilation. Defaults to current directory.
        """
        self.base_dir = Path(base_dir)
        self.warnings: list[str] = []
        self.errors: list[str] = []
        self._logger = None

    def _log(self, method: str, message: str, **kwargs):
        """Delegate to logger if available, else no-op."""
        if self._logger:
            getattr(self._logger, method)(message, **kwargs)

    def compile(
        self, config: CompilationConfig, primitives: PrimitiveCollection | None = None, logger=None
    ) -> CompilationResult:
        return _class_compile.compile(self, config, primitives, logger)

    def _compile_agents_md(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        return _class_compile._compile_agents_md(self, config, primitives)

    def _compile_distributed(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        return _class_compile._compile_distributed(self, config, primitives)

    def _compile_single_file(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        return _class_compile._compile_single_file(self, config, primitives)

    def _compile_claude_md(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        return _claude_gemini._compile_claude_md(self, config, primitives)

    def _compile_gemini_md(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        return _claude_gemini._compile_gemini_md(self, config, primitives)

    def _merge_results(self, results: list[CompilationResult]) -> CompilationResult:
        return _claude_gemini._merge_results(self, results)

    def validate_primitives(self, primitives: PrimitiveCollection) -> list[str]:
        """Validate primitives for compilation.

        Args:
            primitives (PrimitiveCollection): Collection of primitives to validate.

        Returns:
            List[str]: List of validation errors.
        """
        errors = []

        # Validate each primitive
        for primitive in primitives.all_primitives():
            primitive_errors = primitive.validate()
            if primitive_errors:
                file_path = portable_relpath(primitive.file_path, self.base_dir)

                for error in primitive_errors:
                    # Treat validation errors as warnings instead of hard errors
                    # This allows compilation to continue with incomplete primitives
                    self.warnings.append(f"{file_path}: {error}")

            # Validate markdown links in each primitive's content using its own directory as base
            if hasattr(primitive, "content") and primitive.content:
                primitive_dir = primitive.file_path.parent
                link_errors = validate_link_targets(primitive.content, primitive_dir)
                if link_errors:
                    file_path = portable_relpath(primitive.file_path, self.base_dir)

                    for link_error in link_errors:
                        self.warnings.append(f"{file_path}: {link_error}")

        return errors

    def generate_output(self, template_data: TemplateData, config: CompilationConfig) -> str:
        return _output.generate_output(self, template_data, config)

    def _generate_template_data(
        self, primitives: PrimitiveCollection, config: CompilationConfig
    ) -> TemplateData:
        return _output._generate_template_data(self, primitives, config)

    def _maybe_emit_copilot_root_instructions(
        self, config: CompilationConfig, primitives: PrimitiveCollection, result: CompilationResult
    ) -> CompilationResult:
        return _copilot_root._maybe_emit_copilot_root_instructions(self, config, primitives, result)

    def _generate_copilot_root_instructions_content(
        self, instructions, config: CompilationConfig
    ) -> str:
        return _copilot_root._generate_copilot_root_instructions_content(self, instructions, config)

    def _finalize_build_id(self, content: str) -> str:
        """Replace the build-id placeholder with a deterministic content hash."""
        lines = content.splitlines()
        try:
            idx = lines.index(BUILD_ID_PLACEHOLDER)
        except ValueError:
            return content

        hash_input_lines = [line for i, line in enumerate(lines) if i != idx]
        build_id = hashlib.sha256("\n".join(hash_input_lines).encode("utf-8")).hexdigest()[:12]
        lines[idx] = f"<!-- Build ID: {build_id} -->"
        return "\n".join(lines) + ("\n" if content.endswith("\n") else "")

    def _cleanup_copilot_root_instructions(
        self, output_path: Path, result: CompilationResult
    ) -> CompilationResult:
        return _copilot_root._cleanup_copilot_root_instructions(self, output_path, result)

    def _write_output_file(self, output_path: str, content: str) -> None:
        return _output._write_output_file(self, output_path, content)

    def _compile_stats(
        self, primitives: PrimitiveCollection, template_data: TemplateData
    ) -> dict[str, Any]:
        return _output._compile_stats(self, primitives, template_data)

    def _write_distributed_file(
        self, agents_path: Path, content: str, config: CompilationConfig
    ) -> None:
        return _output._write_distributed_file(self, agents_path, content, config)

    def _display_placement_preview(self, distributed_result) -> None:
        return _display._display_placement_preview(self, distributed_result)

    def _display_trace_info(self, distributed_result, primitives: PrimitiveCollection) -> None:
        return _display._display_trace_info(self, distributed_result, primitives)

    def _generate_placement_summary(self, distributed_result) -> str:
        return _display._generate_placement_summary(self, distributed_result)

    def _generate_distributed_summary(self, distributed_result, config: CompilationConfig) -> str:
        return _display._generate_distributed_summary(self, distributed_result, config)


def compile_agents_md(
    primitives: PrimitiveCollection | None = None,
    output_path: str = "AGENTS.md",
    chatmode: str | None = None,
    dry_run: bool = False,
    base_dir: str = ".",
) -> str:
    """Generate AGENTS.md with conditional sections.

    Args:
        primitives (Optional[PrimitiveCollection]): Primitives to use, or None to discover.
        output_path (str): Output file path. Defaults to "AGENTS.md".
        chatmode (str): Specific chatmode to use, or None for default.
        dry_run (bool): If True, don't write output file. Defaults to False.
        base_dir (str): Base directory for compilation. Defaults to current directory.

    Returns:
        str: Generated AGENTS.md content.
    """
    # Create configuration - use single-file mode for backward compatibility
    config = CompilationConfig(
        output_path=output_path,
        chatmode=chatmode,
        dry_run=dry_run,
        strategy="single-file",  # Force single-file mode for backward compatibility
    )

    # Create compiler and compile
    compiler = AgentsCompiler(base_dir)
    result = compiler.compile(config, primitives)

    if not result.success:
        raise RuntimeError(f"Compilation failed: {'; '.join(result.errors)}")

    return result.content


from . import class_compile as _class_compile
from . import claude_gemini as _claude_gemini
from . import copilot_root as _copilot_root
from . import display as _display
from . import output as _output
