# pylint: disable=duplicate-code
"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

from __future__ import annotations

import logging
import sys

from ...core.target_detection import (
    should_compile_agents_md,
    should_compile_claude_md,
    should_compile_gemini_md,
)
from ...primitives.models import PrimitiveCollection
from .class_ import CompilationConfig, CompilationResult

_logger = logging.getLogger(__name__)
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "windsurf",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


def _resolve_routing_target(self, config: CompilationConfig) -> tuple:
    """Validate config.target and return (routing_target, error_result | None).

    Returns (routing_target, None) on success, or (None, CompilationResult) on error.
    """
    if isinstance(config.target, frozenset):
        invalid_families = config.target - _KNOWN_COMPILE_FAMILIES
        if invalid_families:
            self.errors.append(
                "Unknown compilation target family in multi-target set: "
                f"{', '.join(sorted(invalid_families))}. "
                "Expected subset of: "
                f"{', '.join(sorted(_KNOWN_COMPILE_FAMILIES))}"
            )
            return None, CompilationResult(
                success=False,
                output_path="",
                content="",
                warnings=self.warnings.copy(),
                errors=self.errors.copy(),
                stats={},
            )
        return config.target, None
    else:
        routing_target = "vscode" if config.target in _VSCODE_TARGET_ALIASES else config.target
        if routing_target not in _KNOWN_TARGETS and config.target not in _KNOWN_TARGETS:
            self.errors.append(
                f"Unknown compilation target: {config.target!r}. "
                f"Expected one of: {', '.join(sorted(set(_KNOWN_TARGETS)))}"
            )
            return None, CompilationResult(
                success=False,
                output_path="",
                content="",
                warnings=self.warnings.copy(),
                errors=self.errors.copy(),
                stats={},
            )
        return routing_target, None


def _build_dry_run_distributed_result(
    self, config: CompilationConfig, distributed_result: CompilationResult
) -> CompilationResult:
    """Build a dry-run CompilationResult from a distributed compile pass."""
    successful_writes = sum(
        1 for agents_path in distributed_result.content_map if agents_path.parent.exists()
    )
    if distributed_result.stats:
        distributed_result.stats["agents_files_generated"] = successful_writes
    return CompilationResult(
        success=True,
        output_path="Preview mode - no files written",
        content=self._generate_placement_summary(distributed_result),
        warnings=self.warnings + distributed_result.warnings,
        errors=self.errors + distributed_result.errors,
        stats=distributed_result.stats,
    )


def compile(
    self,
    config: CompilationConfig,
    primitives: PrimitiveCollection | None = None,
    logger=None,
) -> CompilationResult:
    """Compile AGENTS.md and/or CLAUDE.md based on target configuration.

    Routes compilation to appropriate targets based on config.target:
    - "vscode" or "agents": Generate AGENTS.md + .github/ structure
    - "claude": Generate CLAUDE.md + .claude/ structure
    - "all": Generate both targets

    Args:
        config (CompilationConfig): Compilation configuration.
        primitives (Optional[PrimitiveCollection]): Primitives to use, or None to discover.

    Returns:
        CompilationResult: Result of the compilation.
    """
    self.warnings.clear()
    self.errors.clear()
    self._logger = logger

    try:
        # Use provided primitives or discover them (with dependency support)
        if primitives is None:
            if config.local_only:
                # Use basic discovery for local-only mode
                primitives = sys.modules[__package__].discover_primitives(
                    str(self.base_dir),
                    exclude_patterns=config.exclude,
                )
            else:
                # Use enhanced discovery with dependencies (Task 4 integration)
                from ...primitives.discovery import discover_primitives_with_dependencies

                primitives = discover_primitives_with_dependencies(
                    str(self.base_dir),
                    exclude_patterns=config.exclude,
                )

        # Route to targets based on config.target.
        routing_target, error_result = _resolve_routing_target(self, config)
        if error_result is not None:
            return error_result

        results: list[CompilationResult] = []

        if should_compile_agents_md(routing_target):
            results.append(self._compile_agents_md(config, primitives))

        if should_compile_claude_md(routing_target):
            results.append(self._compile_claude_md(config, primitives))

        if should_compile_gemini_md(routing_target):
            results.append(self._compile_gemini_md(config, primitives))

        # Some targets (e.g. cursor, agent-skills) use the data-driven
        # integration layer and don't need compilation.
        if not results:
            if logger and config.target == "agent-skills":
                logger.progress(
                    "agent-skills -- no compile outputs, skipping",
                    symbol="info",
                )
            return CompilationResult(
                success=True,
                output_path="",
                content="",
                warnings=self.warnings.copy(),
                errors=self.errors.copy(),
                stats={},
            )

        # Merge results from all targets
        return self._merge_results(results)

    except Exception as e:
        self.errors.append(f"Compilation failed: {e!s}")
        return CompilationResult(
            success=False,
            output_path="",
            content="",
            warnings=self.warnings.copy(),
            errors=self.errors.copy(),
            stats={},
        )


def _compile_agents_md(
    self, config: CompilationConfig, primitives: PrimitiveCollection
) -> CompilationResult:
    """Compile AGENTS.md files (VSCode/Copilot target).

    Args:
        config (CompilationConfig): Compilation configuration.
        primitives (PrimitiveCollection): Primitives to compile.

    Returns:
        CompilationResult: Result of the AGENTS.md compilation.
    """
    # Handle distributed compilation (Task 7 - new default behavior)
    if config.strategy == "distributed" and not config.single_agents:
        result = self._compile_distributed(config, primitives)
    else:
        # Traditional single-file compilation (backward compatibility)
        result = self._compile_single_file(config, primitives)

    return self._maybe_emit_copilot_root_instructions(config, primitives, result)


def _compile_distributed(
    self, config: CompilationConfig, primitives: PrimitiveCollection
) -> CompilationResult:
    """Compile using distributed AGENTS.md approach (Task 7).

    Args:
        config (CompilationConfig): Compilation configuration.
        primitives (PrimitiveCollection): Primitives to compile.

    Returns:
        CompilationResult: Result of distributed compilation.
    """
    from ..distributed_compiler import DistributedAgentsCompiler

    errors = self.validate_primitives(primitives)
    self.errors.extend(errors)

    # Create distributed compiler with exclude patterns
    distributed_compiler = DistributedAgentsCompiler(
        str(self.base_dir), exclude_patterns=config.exclude
    )

    # Prepare configuration for distributed compilation
    distributed_config = {
        "min_instructions_per_file": config.min_instructions_per_file,
        # max_depth removed - full project analysis
        "source_attribution": config.source_attribution,
        "debug": config.debug,
        "clean_orphaned": config.clean_orphaned,
        "dry_run": config.dry_run,
    }

    # Compile distributed
    distributed_result = distributed_compiler.compile_distributed(primitives, distributed_config)

    # Display professional compilation output (always show, not just in debug)
    compilation_results = distributed_compiler.get_compilation_results_for_display(config.dry_run)
    if compilation_results:
        if config.debug or config.trace:
            # Verbose mode with mathematical analysis
            output = distributed_compiler.output_formatter.format_verbose(compilation_results)
        elif config.dry_run:
            # Dry run mode with placement preview
            output = distributed_compiler.output_formatter.format_dry_run(compilation_results)
        else:
            # Default mode with essential information
            output = distributed_compiler.output_formatter.format_default(compilation_results)

        # Display the professional output
        self._log("progress", output)

    if not distributed_result.success:
        self.warnings.extend(distributed_result.warnings)
        self.errors.extend(distributed_result.errors)
        return CompilationResult(
            success=False,
            output_path="",
            content="",
            warnings=self.warnings.copy(),
            errors=self.errors.copy(),
            stats=distributed_result.stats,
        )

    # Handle dry-run mode (preview placement without writing files)
    if config.dry_run:
        # Don't write files in preview mode - output already shown above
        return _build_dry_run_distributed_result(self, config, distributed_result)

    # Write distributed AGENTS.md files
    successful_writes = 0
    len(distributed_result.content_map)

    for agents_path, content in distributed_result.content_map.items():
        try:
            self._write_distributed_file(agents_path, content, config)
            successful_writes += 1
        except OSError as e:
            self.errors.append(f"Failed to write {agents_path}: {e!s}")

    # Update stats with actual files written
    if distributed_result.stats:
        distributed_result.stats["agents_files_generated"] = successful_writes

    # Merge warnings and errors
    self.warnings.extend(distributed_result.warnings)
    self.errors.extend(distributed_result.errors)

    # Create summary for backward compatibility
    summary_content = self._generate_distributed_summary(distributed_result, config)

    return CompilationResult(
        success=len(self.errors) == 0,
        output_path=f"Distributed: {len(distributed_result.placements)} AGENTS.md files",
        content=summary_content,
        warnings=self.warnings.copy(),
        errors=self.errors.copy(),
        stats=distributed_result.stats,
    )


def _compile_single_file(
    self, config: CompilationConfig, primitives: PrimitiveCollection
) -> CompilationResult:
    """Compile using traditional single-file approach (backward compatibility).

    Args:
        config (CompilationConfig): Compilation configuration.
        primitives (PrimitiveCollection): Primitives to compile.

    Returns:
        CompilationResult: Result of single-file compilation.
    """
    # Validate primitives
    validation_errors = self.validate_primitives(primitives)
    if validation_errors:
        self.errors.extend(validation_errors)

    # Generate template data
    template_data = self._generate_template_data(primitives, config)

    # Generate final output
    content = self.generate_output(template_data, config)

    # Write output file (constitution injection handled externally in CLI)
    output_path = str(self.base_dir / config.output_path)
    if not config.dry_run:
        self._write_output_file(output_path, content)

    # Compile statistics
    stats = self._compile_stats(primitives, template_data)

    return CompilationResult(
        success=len(self.errors) == 0,
        output_path=output_path,
        content=content,
        warnings=self.warnings.copy(),
        errors=self.errors.copy(),
        stats=stats,
    )
