"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

from __future__ import annotations

import logging
import sys
from typing import Any

from ...primitives.models import PrimitiveCollection
from ...utils.paths import portable_relpath
from ..claude_formatter import ClaudeFormatter
from .class_ import CompilationConfig, CompilationResult

_logger = logging.getLogger(__name__)
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "windsurf",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


def _write_claude_files(
    self,
    claude_result: Any,
    config: Any,
    all_warnings: list,
    all_errors: list,
) -> tuple[int, bool]:
    """Write CLAUDE.md files to disk, running security scans. Returns (files_written, critical_found)."""
    from ...security.gate import WARN_POLICY, SecurityGate
    from ..output_writer import CompiledOutputWriter

    writer = CompiledOutputWriter()
    files_written = 0
    critical_security_found = False

    for claude_path, content in claude_result.content_map.items():
        try:
            final_content = content
            if config.with_constitution:
                try:
                    from ..injector import ConstitutionInjector

                    injector = ConstitutionInjector(str(claude_path.parent))
                    final_content, _, _ = injector.inject(
                        content, with_constitution=True, output_path=claude_path
                    )
                except Exception as exc:
                    sys.modules[__package__]._logger.debug(
                        "Constitution injection failed for %s: %s", claude_path, exc
                    )

            verdict = SecurityGate.scan_text(final_content, str(claude_path), policy=WARN_POLICY)
            actionable = verdict.critical_count + verdict.warning_count
            if actionable:
                if verdict.has_critical:
                    critical_security_found = True
                all_warnings.append(
                    f"CLAUDE.md contains {actionable} hidden character(s) "
                    f"-- run 'apm audit --file {claude_path}' to inspect"
                )

            writer.write(claude_path, final_content)
            files_written += 1
        except OSError as e:
            all_errors.append(f"Failed to write {claude_path}: {e!s}")

    return files_written, critical_security_found


def _compile_claude_md(
    self, config: CompilationConfig, primitives: PrimitiveCollection
) -> CompilationResult:
    """Compile CLAUDE.md files (Claude Code target).

    Uses ClaudeFormatter to generate CLAUDE.md files following Claude's
    Memory format with @import syntax, grouped project standards, and
    workflows section for agents/roles.

    Args:
        config (CompilationConfig): Compilation configuration.
        primitives (PrimitiveCollection): Primitives to compile.

    Returns:
        CompilationResult: Result of the CLAUDE.md compilation.
    """
    errors = self.validate_primitives(primitives)
    self.errors.extend(errors)

    # Create Claude formatter
    claude_formatter = ClaudeFormatter(str(self.base_dir))

    # Get placement map from distributed compiler for consistency
    from ..distributed_compiler import DistributedAgentsCompiler

    distributed_compiler = DistributedAgentsCompiler(
        str(self.base_dir), exclude_patterns=config.exclude
    )

    # Analyze directory structure and determine placement
    directory_map = distributed_compiler.analyze_directory_structure(primitives.instructions)
    placement_map = distributed_compiler.determine_agents_placement(
        primitives.instructions,
        directory_map,
        min_instructions=config.min_instructions_per_file,
        debug=config.debug,
    )

    # Format CLAUDE.md files
    claude_config = {"source_attribution": config.source_attribution, "debug": config.debug}
    claude_result = claude_formatter.format_distributed(primitives, placement_map, claude_config)

    # NOTE: Claude commands are now generated at install time via CommandIntegrator,
    # not at compile time. This keeps behavior consistent with VSCode prompt integration.

    # Merge warnings and errors (no command result anymore)
    all_warnings = self.warnings + claude_result.warnings
    all_errors = self.errors + claude_result.errors

    # Handle dry-run mode
    if config.dry_run:
        # Generate preview summary
        preview_lines = [f"CLAUDE.md Preview: Would generate {len(claude_result.placements)} files"]
        for claude_path in claude_result.content_map:
            rel_path = portable_relpath(claude_path, self.base_dir)
            preview_lines.append(f"  {rel_path}")

        return CompilationResult(
            success=len(all_errors) == 0,
            output_path="Preview mode - CLAUDE.md",
            content="\n".join(preview_lines),
            warnings=all_warnings,
            errors=all_errors,
            stats=claude_result.stats,
        )

    # Write CLAUDE.md files
    files_written, critical_security_found = _write_claude_files(
        self, claude_result, config, all_warnings, all_errors
    )

    # Update stats
    stats = claude_result.stats.copy()
    stats["claude_files_written"] = files_written

    # Display CLAUDE.md compilation output using standard formatter
    # Get proper compilation results from distributed compiler (has optimization decisions)
    from ...output.formatters import CompilationFormatter
    from ...output.models import CompilationResults

    compilation_results = distributed_compiler.get_compilation_results_for_display(
        is_dry_run=config.dry_run
    )
    if compilation_results:
        # Update target name for CLAUDE.md output
        formatter_results = CompilationResults(
            project_analysis=compilation_results.project_analysis,
            optimization_decisions=compilation_results.optimization_decisions,
            placement_summaries=compilation_results.placement_summaries,
            optimization_stats=compilation_results.optimization_stats,
            warnings=all_warnings,
            errors=all_errors,
            is_dry_run=config.dry_run,
            target_name="CLAUDE.md",
        )

        # Use the same formatter as AGENTS.md
        formatter = CompilationFormatter(use_color=True)
        if config.debug or config.trace:
            output = formatter.format_verbose(formatter_results)
        elif config.dry_run:
            output = formatter.format_dry_run(formatter_results)
        else:
            output = formatter.format_default(formatter_results)
        self._log("progress", output)

    # Generate summary content for result object
    summary_lines = [
        "# CLAUDE.md Compilation Summary",
        "",
        f"Generated {files_written} CLAUDE.md files:",
    ]
    for placement in claude_result.placements:
        rel_path = portable_relpath(placement.claude_path, self.base_dir)
        summary_lines.append(f"- {rel_path} ({len(placement.instructions)} instructions)")

    return CompilationResult(
        success=len(all_errors) == 0,
        output_path=f"CLAUDE.md: {files_written} files",
        content="\n".join(summary_lines),
        warnings=all_warnings,
        errors=all_errors,
        stats=stats,
        has_critical_security=critical_security_found,
    )


def _compile_gemini_md(
    self, config: CompilationConfig, primitives: PrimitiveCollection
) -> CompilationResult:
    """Compile GEMINI.md stub that imports AGENTS.md.

    Gemini CLI supports ``@./path`` import syntax, so GEMINI.md is a
    thin wrapper that pulls in AGENTS.md at load time.  The actual
    instruction roll-up is handled by the AGENTS.md pipeline (which
    is always compiled alongside via ``should_compile_agents_md``).

    Args:
        config: Compilation configuration.
        primitives: Primitives to compile.

    Returns:
        CompilationResult for the GEMINI.md compilation.
    """
    from ..gemini_formatter import GeminiFormatter

    gemini_formatter = GeminiFormatter(str(self.base_dir))
    gemini_result = gemini_formatter.format_distributed(primitives)

    all_warnings = self.warnings + gemini_result.warnings
    all_errors = self.errors + gemini_result.errors

    if config.dry_run:
        return CompilationResult(
            success=len(all_errors) == 0,
            output_path="Preview mode - GEMINI.md",
            content="GEMINI.md Preview: Would generate stub importing AGENTS.md",
            warnings=all_warnings,
            errors=all_errors,
            stats=gemini_result.stats,
        )

    files_written = 0
    from ..output_writer import CompiledOutputWriter

    writer = CompiledOutputWriter()
    for gemini_path, content in gemini_result.content_map.items():
        try:
            writer.write(gemini_path, content)
            files_written += 1
        except OSError as e:
            all_errors.append(f"Failed to write {gemini_path}: {e!s}")

    stats = gemini_result.stats.copy()
    stats["gemini_files_written"] = files_written

    self._log("progress", "Generated GEMINI.md (imports AGENTS.md)")

    return CompilationResult(
        success=len(all_errors) == 0,
        output_path=f"GEMINI.md: {files_written} files",
        content=f"Generated {files_written} GEMINI.md stub importing AGENTS.md",
        warnings=all_warnings,
        errors=all_errors,
        stats=stats,
    )


def _merge_results(self, results: list[CompilationResult]) -> CompilationResult:
    """Merge multiple compilation results into a single result.

    Combines warnings, errors, stats, and content from multiple target
    compilations into a unified result.

    Args:
        results (List[CompilationResult]): List of compilation results to merge.

    Returns:
        CompilationResult: Merged compilation result.
    """
    if not results:
        return CompilationResult(
            success=True, output_path="", content="", warnings=[], errors=[], stats={}
        )

    if len(results) == 1:
        return results[0]

    # Merge all results
    merged_warnings: list[str] = []
    merged_errors: list[str] = []
    merged_stats: dict[str, Any] = {}
    output_paths: list[str] = []
    content_parts: list[str] = []

    for result in results:
        merged_warnings.extend(result.warnings)
        merged_errors.extend(result.errors)

        # Merge stats with prefixes to avoid collisions
        for key, value in result.stats.items():
            if key in merged_stats:
                # Handle numeric stats by summing
                if isinstance(value, (int, float)) and isinstance(merged_stats[key], (int, float)):
                    merged_stats[key] = merged_stats[key] + value
            else:
                merged_stats[key] = value

        if result.output_path:
            output_paths.append(result.output_path)
        if result.content:
            content_parts.append(result.content)

    # Determine overall success
    overall_success = all(r.success for r in results)

    return CompilationResult(
        success=overall_success,
        output_path=" | ".join(output_paths) if output_paths else "",
        content="\n\n---\n\n".join(content_parts) if content_parts else "",
        warnings=merged_warnings,
        errors=merged_errors,
        stats=merged_stats,
        has_critical_security=any(r.has_critical_security for r in results),
    )
