# pylint: disable=duplicate-code
"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

from ...core.target_detection import (
    should_compile_copilot_instructions_md,
)
from ...primitives.models import PrimitiveCollection
from ...utils.paths import portable_relpath
from ...version import get_version
from ..constants import BUILD_ID_PLACEHOLDER
from ..link_resolver import resolve_markdown_links
from .class_ import CompilationConfig, CompilationResult

_logger = logging.getLogger(__name__)
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "windsurf",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


def _init_no_output_result(
    self,
    result: CompilationResult,
    config: CompilationConfig,
    output_path: Path,
) -> CompilationResult:
    """Populate zero stats and optionally clean up the output file.

    Used when copilot-instructions.md compilation is skipped because the
    routing target does not produce that file, or because there are no
    global instruction primitives.
    """
    if not config.dry_run:
        self._cleanup_copilot_root_instructions(output_path, result)
    result.stats.setdefault("copilot_root_instructions_generated", 0)
    result.stats.setdefault("copilot_root_instructions_written", 0)
    result.stats.setdefault("copilot_root_instructions_unchanged", 0)
    result.stats.setdefault("copilot_root_instructions_skipped", 0)
    result.stats.setdefault("copilot_root_instructions_removed", 0)
    return result


@dataclass(frozen=True, slots=True)
class _CopilotRootWriteContext:
    """Inputs required to finalise copilot root output."""

    output_path: Path
    content: str
    existing: str | None
    dry_run: bool


def _finalize_copilot_root_write(
    self,
    result: CompilationResult,
    context: _CopilotRootWriteContext,
) -> CompilationResult:
    """Write copilot-instructions.md unless unchanged or running dry.

    Handles the unchanged check, dry-run early exit, SecurityGate scan,
    and the actual write (including any OSError).
    """
    if context.existing == context.content:
        result.stats["copilot_root_instructions_written"] = 0
        result.stats["copilot_root_instructions_unchanged"] = 1
        return result

    if context.dry_run:
        return result

    from ...security.gate import WARN_POLICY, SecurityGate

    verdict = SecurityGate.scan_text(context.content, str(context.output_path), policy=WARN_POLICY)
    actionable = verdict.critical_count + verdict.warning_count
    if actionable:
        if verdict.has_critical:
            result.has_critical_security = True
        result.warnings.append(
            f"copilot-instructions.md contains {actionable} hidden character(s) "
            f"-- run 'apm audit --file {context.output_path}' to inspect"
        )

    try:
        context.output_path.parent.mkdir(parents=True, exist_ok=True)
        context.output_path.write_text(context.content, encoding="utf-8")
        result.stats["copilot_root_instructions_written"] = 1
        result.stats["copilot_root_instructions_unchanged"] = 0
        return result
    except OSError as exc:
        message = f"Failed to write {context.output_path}: {exc}"
        self.errors.append(message)
        result.errors.append(message)
        result.success = False
        result.stats["copilot_root_instructions_written"] = 0
        result.stats.setdefault("copilot_root_instructions_unchanged", 0)
        return result


def _maybe_emit_copilot_root_instructions(
    self,
    config: CompilationConfig,
    primitives: PrimitiveCollection,
    result: CompilationResult,
) -> CompilationResult:
    """Generate .github/copilot-instructions.md for Copilot-capable targets.

    Skip semantics: if the file already exists without the APM-generated
    marker, it is treated as hand-authored and left untouched. The
    ``copilot_root_instructions_skipped`` stat captures this case
    explicitly so callers can distinguish it from a genuine no-op
    (``copilot_root_instructions_unchanged``) or an unrouted target.
    """
    routing_target = "vscode" if config.target in _VSCODE_TARGET_ALIASES else config.target
    output_path = self.base_dir / ".github" / "copilot-instructions.md"
    if not should_compile_copilot_instructions_md(routing_target):
        return _init_no_output_result(self, result, config, output_path)

    global_instructions = sorted(
        [instruction for instruction in primitives.instructions if not instruction.apply_to],
        key=lambda instruction: portable_relpath(instruction.file_path, self.base_dir),
    )
    if not global_instructions:
        return _init_no_output_result(self, result, config, output_path)

    content = self._generate_copilot_root_instructions_content(global_instructions, config)

    result.stats["copilot_root_instructions_generated"] = 1
    result.stats.setdefault("copilot_root_instructions_skipped", 0)
    result.stats.setdefault("copilot_root_instructions_removed", 0)
    result.stats.setdefault("copilot_root_instructions_written", 0)
    result.stats.setdefault("copilot_root_instructions_unchanged", 0)

    # Inspect any existing file BEFORE the dry-run early-exit so that
    # `--dry-run` faithfully reports what a real run would do (skip vs
    # write vs unchanged). Reading the file here is safe in dry-run mode
    # because we never mutate it.
    try:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else None
    except OSError as exc:
        message = f"Failed to read {output_path}: {exc}"
        self.errors.append(message)
        result.errors.append(message)
        result.success = False
        return result

    if existing is not None and _COPILOT_ROOT_GENERATED_MARKER not in existing:
        rel_path = portable_relpath(output_path, self.base_dir)
        result.warnings.append(
            f"Skipped {rel_path}: hand-authored file will not be overwritten. "
            "To regenerate, either delete or rename it, or prepend the line "
            f"'{_COPILOT_ROOT_GENERATED_MARKER}' to the top of the file. "
            "Then re-run 'apm compile'."
        )
        # The file was never compared to new content; record as
        # 'skipped', not 'unchanged'. Also reset 'generated' since no
        # output was actually emitted (or would be, on a real run).
        result.stats["copilot_root_instructions_generated"] = 0
        result.stats["copilot_root_instructions_written"] = 0
        result.stats["copilot_root_instructions_skipped"] = 1
        result.stats["copilot_root_instructions_unchanged"] = 0
        return result

    return _finalize_copilot_root_write(
        self,
        result,
        _CopilotRootWriteContext(
            output_path=output_path,
            content=content,
            existing=existing,
            dry_run=config.dry_run,
        ),
    )


def _generate_copilot_root_instructions_content(
    self,
    instructions,
    config: CompilationConfig,
) -> str:
    """Generate root Copilot instructions content from global instruction primitives."""
    sections = [
        _COPILOT_ROOT_GENERATED_MARKER,
        BUILD_ID_PLACEHOLDER,
        f"<!-- APM Version: {get_version()} -->",
        "",
    ]

    for instruction in instructions:
        rel_path = portable_relpath(instruction.file_path, self.base_dir)
        sections.append(f"<!-- Source: {rel_path} -->")
        sections.append(instruction.content.strip())
        sections.append(f"<!-- End source: {rel_path} -->")
        sections.append("")

    sections.append("---")
    sections.append("*This file was generated by APM CLI. Do not edit manually.*")
    sections.append("*To regenerate: `apm compile`*")
    sections.append("")

    content = "\n".join(sections)
    if config.resolve_links:
        content = resolve_markdown_links(content, self.base_dir)
    return self._finalize_build_id(content)


def _cleanup_copilot_root_instructions(
    self,
    output_path: Path,
    result: CompilationResult,
) -> CompilationResult:
    """Remove stale generated Copilot root instructions when no longer applicable."""
    if not output_path.exists():
        result.stats.setdefault("copilot_root_instructions_removed", 0)
        return result

    try:
        existing = output_path.read_text(encoding="utf-8")
        if _COPILOT_ROOT_GENERATED_MARKER not in existing:
            result.stats.setdefault("copilot_root_instructions_removed", 0)
            return result

        output_path.unlink()
        result.stats["copilot_root_instructions_removed"] = 1
        return result
    except OSError as exc:
        message = f"Failed to remove stale {output_path}: {exc}"
        self.errors.append(message)
        result.errors.append(message)
        result.success = False
        result.stats.setdefault("copilot_root_instructions_removed", 0)
        return result
