# pylint: disable=duplicate-code
"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

import logging

from ...primitives.models import PrimitiveCollection
from ...utils.paths import portable_relpath
from .class_ import CompilationConfig

_logger = logging.getLogger(__name__)
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "windsurf",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


def _display_placement_preview(self, distributed_result) -> None:
    """Display placement preview for --show-placement mode.

    Args:
        distributed_result: Result from distributed compilation.
    """
    self._log("progress", "Distributed AGENTS.md Placement Preview:")
    self._log("progress", "")

    for placement in distributed_result.placements:
        rel_path = portable_relpath(placement.agents_path, self.base_dir)
        self._log("verbose_detail", f"{rel_path}")
        self._log("verbose_detail", f"   Instructions: {len(placement.instructions)}")
        self._log(
            "verbose_detail", f"   Patterns: {', '.join(sorted(placement.coverage_patterns))}"
        )
        if placement.source_attribution:
            sources = set(placement.source_attribution.values())
            self._log("verbose_detail", f"   Sources: {', '.join(sorted(sources))}")
        self._log("verbose_detail", "")


def _display_trace_info(self, distributed_result, primitives: PrimitiveCollection) -> None:
    """Display detailed trace information for --trace mode.

    Args:
        distributed_result: Result from distributed compilation.
        primitives (PrimitiveCollection): Full primitive collection.
    """
    self._log("progress", "Distributed Compilation Trace:")
    self._log("progress", "")

    for placement in distributed_result.placements:
        rel_path = portable_relpath(placement.agents_path, self.base_dir)
        self._log("verbose_detail", f"{rel_path}")

        for instruction in placement.instructions:
            source = getattr(instruction, "source", "local")
            inst_path = portable_relpath(instruction.file_path, self.base_dir)

            self._log(
                "verbose_detail",
                f"   * {instruction.apply_to or 'no pattern'} <- {source} {inst_path}",
            )
        self._log("verbose_detail", "")


def _generate_placement_summary(self, distributed_result) -> str:
    """Generate a text summary of placement results.

    Args:
        distributed_result: Result from distributed compilation.

    Returns:
        str: Text summary of placements.
    """
    lines = ["Distributed AGENTS.md Placement Summary:", ""]

    for placement in distributed_result.placements:
        rel_path = portable_relpath(placement.agents_path, self.base_dir)
        lines.append(f"{rel_path}")
        lines.append(f"   Instructions: {len(placement.instructions)}")
        lines.append(f"   Patterns: {', '.join(sorted(placement.coverage_patterns))}")
        lines.append("")

    lines.append(f"Total AGENTS.md files: {len(distributed_result.placements)}")
    return "\n".join(lines)


def _generate_distributed_summary(self, distributed_result, config: CompilationConfig) -> str:
    """Generate a summary of distributed compilation results.

    Args:
        distributed_result: Result from distributed compilation.
        config (CompilationConfig): Compilation configuration.

    Returns:
        str: Summary content.
    """
    lines = [
        "# Distributed AGENTS.md Compilation Summary",
        "",
        f"Generated {len(distributed_result.placements)} AGENTS.md files:",
        "",
    ]

    for placement in distributed_result.placements:
        rel_path = portable_relpath(placement.agents_path, self.base_dir)
        lines.append(f"- {rel_path} ({len(placement.instructions)} instructions)")

    lines.extend(
        [
            "",
            f"Total instructions: {distributed_result.stats.get('total_instructions_placed', 0)}",
            f"Total patterns: {distributed_result.stats.get('total_patterns_covered', 0)}",
            "",
            "Use 'apm compile --single-agents' for traditional single-file compilation.",
        ]
    )

    return "\n".join(lines)
