# pylint: disable=duplicate-code
"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

import logging
from pathlib import Path
from typing import Any

from ...primitives.models import PrimitiveCollection
from ...version import get_version
from ..link_resolver import resolve_markdown_links
from ..template_builder import (
    TemplateData,
    build_conditional_sections,
    find_chatmode_by_name,
    generate_agents_md_template,
)
from .class_ import CompilationConfig

_logger = logging.getLogger(__name__)
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "windsurf",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


def generate_output(self, template_data: TemplateData, config: CompilationConfig) -> str:
    """Generate the final AGENTS.md output.

    Args:
        template_data (TemplateData): Data for template generation.
        config (CompilationConfig): Compilation configuration.

    Returns:
        str: Generated AGENTS.md content.
    """
    content = generate_agents_md_template(template_data)

    # Resolve markdown links if enabled
    if config.resolve_links:
        content = resolve_markdown_links(content, self.base_dir)

    return content


def _generate_template_data(
    self, primitives: PrimitiveCollection, config: CompilationConfig
) -> TemplateData:
    """Generate template data from primitives and configuration.

    Args:
        primitives (PrimitiveCollection): Discovered primitives.
        config (CompilationConfig): Compilation configuration.

    Returns:
        TemplateData: Template data for generation.
    """
    # Build instructions content
    instructions_content = build_conditional_sections(primitives.instructions)

    # Metadata (version only; timestamp intentionally omitted for determinism)
    version = get_version()

    # Handle chatmode content
    chatmode_content = None
    if config.chatmode:
        chatmode = find_chatmode_by_name(primitives.chatmodes, config.chatmode)
        if chatmode:
            chatmode_content = chatmode.content
        else:
            self.warnings.append(f"Chatmode '{config.chatmode}' not found")

    return TemplateData(
        instructions_content=instructions_content,
        version=version,
        chatmode_content=chatmode_content,
    )


def _write_output_file(self, output_path: str, content: str) -> None:
    """Write the generated content to the output file.

    Args:
        output_path (str): Path to write the output.
        content (str): Content to write.
    """
    from ..output_writer import CompiledOutputWriter

    try:
        CompiledOutputWriter().write(Path(output_path), content)
    except OSError as e:
        self.errors.append(f"Failed to write output file {output_path}: {e!s}")


def _compile_stats(
    self, primitives: PrimitiveCollection, template_data: TemplateData
) -> dict[str, Any]:
    """Compile statistics about the compilation.

    Args:
        primitives (PrimitiveCollection): Discovered primitives.
        template_data (TemplateData): Generated template data.

    Returns:
        Dict[str, Any]: Compilation statistics.
    """
    return {
        "primitives_found": primitives.count(),
        "chatmodes": len(primitives.chatmodes),
        "instructions": len(primitives.instructions),
        "contexts": len(primitives.contexts),
        "content_length": len(template_data.instructions_content),
        # timestamp removed
        "version": template_data.version,
    }


def _write_distributed_file(
    self, agents_path: Path, content: str, config: CompilationConfig
) -> None:
    """Write a distributed AGENTS.md file with constitution injection support.

    Args:
        agents_path (Path): Path to write the AGENTS.md file.
        content (str): Content to write.
        config (CompilationConfig): Compilation configuration.
    """
    try:
        # Handle constitution injection for distributed files
        final_content = content

        if config.with_constitution:
            # Try to inject constitution if available
            try:
                from ..injector import ConstitutionInjector

                injector = ConstitutionInjector(str(agents_path.parent))
                final_content, _c_status, _c_hash = injector.inject(
                    content, with_constitution=True, output_path=agents_path
                )
            except Exception as exc:
                _logger.debug("Constitution injection failed for %s: %s", agents_path, exc)

        from ..output_writer import CompiledOutputWriter

        CompiledOutputWriter().write(agents_path, final_content)

    except OSError as e:
        raise OSError(f"Failed to write distributed AGENTS.md file {agents_path}: {e!s}")  # noqa: B904
