"""Installed-CLI regression coverage for AGENTS.md source attribution."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from apm_cli.compilation.distributed_compiler import AGENTS_MD_GENERATED_MARKER

pytestmark = [
    pytest.mark.integration,
    pytest.mark.e2e,
    pytest.mark.lifecycle_smoke,
    pytest.mark.requires_apm_binary,
    pytest.mark.requires_e2e_mode,
]

_VERSION_COMMENT = "<!-- APM Version:"
_SOURCE_COMMENT = "<!-- Source:"
_SOURCES_COMMENT = "<!-- Sources:"
_FOOTER = "*This file was generated by APM CLI. Do not edit manually.*"


def _create_project(project: Path) -> None:
    """Create a minimal codex project with attribution disabled in its manifest."""
    (project / "apm.yml").write_text(
        "name: agents-source-attribution\n"
        "version: 0.1.0\n"
        "targets:\n"
        "  - codex\n"
        "compilation:\n"
        "  source_attribution: false\n",
        encoding="ascii",
    )
    instructions = project / ".apm" / "instructions"
    instructions.mkdir(parents=True)
    (instructions / "demo.instructions.md").write_text(
        "---\ndescription: Demo instruction\napplyTo: '**'\n---\n# Demo\nUse focused tests.\n",
        encoding="ascii",
    )


def test_installed_compile_suppresses_only_cosmetic_agents_annotations(
    tmp_path: Path, apm_binary_path: Path
) -> None:
    """The manifest flag must survive the installed CLI lifecycle for codex."""
    project = tmp_path / "project"
    project.mkdir()
    _create_project(project)

    result = subprocess.run(
        (str(apm_binary_path), "compile", "--target", "codex"),
        cwd=project,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr or result.stdout
    rendered = (project / "AGENTS.md").read_text(encoding="utf-8")
    assert _VERSION_COMMENT not in rendered
    assert _SOURCE_COMMENT not in rendered
    assert _SOURCES_COMMENT not in rendered
    assert _FOOTER not in rendered
    assert AGENTS_MD_GENERATED_MARKER in rendered
    assert "<!-- Build ID:" in rendered
