"""Architecture guardrails for generated-content footer wording."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.architecture_linter.inventory import build_inventory
from scripts.architecture_linter.registry import load_registry
from scripts.architecture_linter.runner import registered_rules, run_selected_rules

pytestmark = pytest.mark.component

ROOT = Path(__file__).parents[2]
RULE_ID = "contracts-tooling-generation-footer"
OWNER = "src/apm_cli/compilation/footer.py"
CONSUMER = "src/apm_cli/compilation/template_builder.py"


def test_generated_footer_has_single_registered_owner_and_guard() -> None:
    """The registry and explicit rule catalog name the footer authority."""
    inventory = build_inventory(ROOT)
    registry = load_registry(ROOT / ".apm/architecture/owners", inventory.files)
    owner = next(
        entry for entry in registry.owners if entry.id == "generated-content-footer-wording"
    )

    assert owner.selectors == (OWNER,)
    assert owner.guards == (RULE_ID,)
    assert RULE_ID in {rule.id for rule in registered_rules()}


def test_generated_footer_rule_rejects_parallel_wording() -> None:
    """The registered guard rejects footer wording duplicated by a renderer."""
    source = (ROOT / CONSUMER).read_text(encoding="utf-8")
    report = run_selected_rules(
        ROOT,
        (RULE_ID,),
        source_overrides={
            CONSUMER: source
            + '\n_DUPLICATE_FOOTER = "This file was generated by APM CLI. '
            + 'Do not edit manually."\n'
        },
    )

    assert any(
        violation.rule_id == RULE_ID
        and violation.path == CONSUMER
        and "duplicates" in violation.message
        for violation in report.violations
    )


def test_generated_footer_rule_requires_executable_consumer_call() -> None:
    """A comment mentioning the owner does not satisfy the registered guard."""
    source = (ROOT / CONSUMER).read_text(encoding="utf-8")
    mutated = source.replace(
        "sections.extend(build_generation_footer(agents_md_mode))",
        "sections.extend([])  # build_generation_footer( is not executable",
    )
    assert mutated != source

    report = run_selected_rules(
        ROOT,
        (RULE_ID,),
        source_overrides={CONSUMER: mutated},
    )

    assert any(
        violation.rule_id == RULE_ID
        and violation.path == CONSUMER
        and "must use build_generation_footer" in violation.message
        for violation in report.violations
    )
