"""Integration coverage for user-scope global compilation."""

from __future__ import annotations

from click.testing import CliRunner


def test_install_global_hints_compile_and_writes_no_root_file(tmp_path, monkeypatch):
    """`apm install -g` prints the compile hint but writes NO root context file.

    Compilation stays explicit: install only nudges the user toward
    `apm compile -g` when global instructions land on a root-context target.
    """
    from apm_cli.commands.install import install as install_cmd
    from apm_cli.primitives.discovery import clear_discovery_cache

    home = tmp_path / "home"
    package_dir = tmp_path / "global-package"
    instruction_dir = package_dir / ".apm" / "instructions"
    instruction_dir.mkdir(parents=True)
    (package_dir / "apm.yml").write_text(
        "name: global-package\nversion: 0.1.0\n",
        encoding="utf-8",
    )
    (instruction_dir / "global.instructions.md").write_text(
        "---\ndescription: Global install instructions\n---\nUse integration tests.\n",
        encoding="utf-8",
    )

    claude_config = home / "claude-config"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_config))
    clear_discovery_cache()

    result = CliRunner().invoke(install_cmd, ["-g", str(package_dir), "--target", "claude"])

    clear_discovery_cache()
    assert result.exit_code == 0, result.output
    # No root context file is written on install -- compilation is explicit.
    assert not (claude_config / "CLAUDE.md").exists()
    # The install nudges the user toward the explicit transform.
    assert "apm compile -g" in result.output


def test_compile_global_writes_claude_md_from_real_fixtures(tmp_path, monkeypatch):
    """Run apm compile --global through real discovery and filesystem writes."""
    from apm_cli.commands.compile.cli import compile as compile_cmd
    from apm_cli.primitives.discovery import clear_discovery_cache

    home = tmp_path / "home"
    apm_modules = home / ".apm" / "apm_modules"
    instruction_dir = apm_modules / "demo" / ".apm" / "instructions"
    instruction_dir.mkdir(parents=True)
    (instruction_dir / "global.instructions.md").write_text(
        "---\ndescription: Global test instructions\n---\nUse type hints in generated code.\n",
        encoding="utf-8",
    )

    claude_config = home / "claude-config"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_config))
    clear_discovery_cache()

    result = CliRunner().invoke(compile_cmd, ["--global"])

    clear_discovery_cache()
    assert result.exit_code == 0, result.output
    output_path = claude_config / "CLAUDE.md"
    content = output_path.read_text(encoding="utf-8")
    assert "<!-- Generated by APM CLI" in content
    assert "Use type hints in generated code." in content
