"""Mixin: orphan-file handling methods for DistributedAgentsCompiler.

Extracted from distributed_compiler.DistributedAgentsCompiler to stay under
the 800-line guardrail (Strangler Stage 2 / issue #1078).

No Rule B routing is required: none of the methods here reference the
module-level names patched by tests (build_attributed_instructions,
UnifiedLinkResolver, ContextOptimizer, CompilationFormatter, CompilationResults).
"""

from __future__ import annotations

import builtins
import logging
from collections.abc import MutableMapping

from ..utils.paths import portable_relpath
from .constitution import find_constitution

_logger = logging.getLogger(__name__)

# Marker present in every APM-generated distributed AGENTS.md. Used to gate
# --clean deletion: files without this marker are hand-authored and must never
# be removed automatically. Public (no leading underscore) because it is a
# stable contract surface depended on by tests and re-exported from
# distributed_compiler. Mirrors the public CLAUDE_HEADER marker on the Claude path.
AGENTS_MD_GENERATED_MARKER = "<!-- Generated by APM CLI from distributed .apm/ primitives -->"


class _DistributedOrphansMixin:
    """Mixin: orphan AGENTS.md detection/cleanup, empty-shell detection, and coverage validation."""

    def _is_placement_empty_shell(
        self,
        placement,
        *,
        with_constitution: bool = True,
        constitution_cache: MutableMapping | None = None,
    ) -> bool:
        """Return True when a placement would produce a content-free AGENTS.md shell.

        This method is only called when ``skip_instructions=True`` (instructions
        are already in ``.github/instructions/`` and will be omitted from output).
        Given that, the only content that could make a placement non-empty is a
        constitution injected at write time.

        Uses the placement model rather than string-parsing rendered content so
        the check stays correct regardless of header/footer layout changes.

        The ``with_constitution`` flag mirrors ``CompilationConfig.with_constitution``
        and resolves the predicate/writer disagreement: if ``--no-constitution`` was
        passed (``with_constitution=False``), the writer will skip injection even when
        a constitution file exists, so the predicate must agree and report "empty".

        Target logic:
            empty = not (with_constitution and constitution_exists(placement.agents_path.parent))

        Args:
            placement: The placement to evaluate.
            with_constitution: Whether the caller will inject a constitution at
                write time (mirrors ``CompilationConfig.with_constitution``).
                Defaults to True for back-compat.
            constitution_cache: Optional mutable mapping keyed by placement
                directory, used to memoize constitution-existence checks across
                placements within a single ``compile_distributed()`` call so the
                same directory is not read from disk repeatedly. When omitted,
                the check reads from disk directly (back-compat for direct callers).

        Returns:
            bool: True if writing this placement would produce a content-free file.
        """
        # When with_constitution is False the writer skips injection regardless of
        # what is on disk, so short-circuit without touching the filesystem.
        if not with_constitution:
            return True

        # ConstitutionInjector uses agents_path.parent as its base_dir, so mirror
        # that here. Memoize per directory to avoid repeated disk I/O in large
        # repos with many placements sharing a tree.
        directory = placement.agents_path.parent
        if constitution_cache is not None and directory in constitution_cache:
            has_constitution = constitution_cache[directory]
        else:
            has_constitution = find_constitution(directory).is_file()
            if constitution_cache is not None:
                constitution_cache[directory] = has_constitution

        return not has_constitution

    @staticmethod
    def _file_has_apm_marker(path) -> bool:
        """Return True if *path* contains the APM-generated marker within its first 4096 bytes.

        Reads only a bounded prefix of the file to avoid loading large AGENTS.md
        files entirely into memory.  Returns False on any OSError (the caller
        should skip the file).
        """
        try:
            with path.open("rb") as fh:
                prefix = fh.read(4096).decode("utf-8", errors="replace")
            return AGENTS_MD_GENERATED_MARKER in prefix
        except OSError:
            return False

    def _find_orphaned_agents_files(
        self,
        generated_paths: builtins.list,
        suppressed_empty_paths: builtins.list | None = None,
    ) -> builtins.list:
        """Find existing AGENTS.md files that weren't generated in the current compilation.

        When ``suppressed_empty_paths`` is provided (non-empty list), those paths
        are also considered candidate orphans so that ``--clean`` can remove stale
        empty shells left by a previous run.  Only files bearing the APM-generated
        marker are ever returned; hand-authored AGENTS.md files are silently skipped.

        Args:
            generated_paths: AGENTS.md placement paths considered part of the current
                run -- these are ALL placement paths (written OR suppressed as empty
                shells), NOT necessarily files that were written to disk.  Paths in
                this list are excluded from orphan candidates so that previously
                written files belonging to an active placement are never flagged for
                cleanup.  Do not pass only the written subset, or stale-but-active
                placements will be incorrectly treated as orphans.
            suppressed_empty_paths: AGENTS.md paths suppressed this run because
                they would have been header/footer-only shells (skip_instructions
                active, no constitution).  Pass an empty list or None when
                ``--clean`` is not in effect.

        Returns:
            List of APM-generated AGENTS.md files that should be cleaned up.
        """
        orphaned_files = []
        generated_set = builtins.set(generated_paths)
        suppressed_set = builtins.set(suppressed_empty_paths or [])

        # Find all existing AGENTS.md files in the project
        for agents_file in self.base_dir.rglob("AGENTS.md"):
            # Skip files that are outside our project or in special directories
            try:
                relative_path = agents_file.resolve().relative_to(self.base_dir.resolve())

                # Skip files in certain directories that shouldn't be cleaned
                skip_dirs = {
                    ".git",
                    ".apm",
                    "node_modules",
                    "__pycache__",
                    ".pytest_cache",
                    "apm_modules",
                }
                if any(part in skip_dirs for part in relative_path.parts):
                    continue

                # Candidate: either a traditional orphan (not in current run)
                # or a suppressed empty shell (skip_instructions active).
                is_traditional_orphan = agents_file not in generated_set
                is_suppressed_empty = agents_file in suppressed_set

                if not is_traditional_orphan and not is_suppressed_empty:
                    continue

                # Marker gate: only touch APM-generated files.  Hand-authored
                # AGENTS.md files (no marker) are never candidates for cleanup.
                # Read only a bounded prefix to limit I/O on large files.
                if not self._file_has_apm_marker(agents_file):
                    continue  # Hand-authored or unreadable -- skip silently

                orphaned_files.append(agents_file)

            except ValueError:
                # File is outside base_dir, skip it
                continue

        return orphaned_files

    def _generate_orphan_warnings(self, orphaned_files: builtins.list) -> builtins.list:
        """Generate warning messages for orphaned AGENTS.md files.

        Args:
            orphaned_files (List[Path]): List of orphaned files to warn about.

        Returns:
            List[str]: List of warning messages.
        """
        warning_messages = []

        if not orphaned_files:
            return warning_messages

        # Professional warning format with readable list for multiple files
        if len(orphaned_files) == 1:
            rel_path = portable_relpath(orphaned_files[0], self.base_dir)
            warning_messages.append(
                f"Orphaned AGENTS.md found: {rel_path} - run 'apm compile --clean' to remove"
            )
        else:
            # For multiple files, create a single multi-line warning message
            file_list = []
            for file_path in orphaned_files[:5]:  # Show first 5
                rel_path = portable_relpath(file_path, self.base_dir)
                file_list.append(f"  * {rel_path}")
            if len(orphaned_files) > 5:
                file_list.append(f"  * ...and {len(orphaned_files) - 5} more")

            # Create one cohesive warning message
            files_text = "\n".join(file_list)
            warning_messages.append(
                f"Found {len(orphaned_files)} orphaned AGENTS.md files:\n{files_text}\n  Run 'apm compile --clean' to remove orphaned files"
            )

        return warning_messages

    def _cleanup_orphaned_files(
        self, orphaned_files: builtins.list, dry_run: bool = False
    ) -> builtins.list:
        """Actually remove orphaned AGENTS.md files.

        Only APM-generated files (those bearing ``AGENTS_MD_GENERATED_MARKER``)
        are removed.  Hand-authored files are skipped silently and recorded at
        DEBUG level only -- no user-facing message is appended to the returned
        list.  (The marker gate is also applied in ``_find_orphaned_agents_files``,
        so reaching the skip branch here is a defense-in-depth path for direct
        callers and is not expected in normal operation.)

        Args:
            orphaned_files: Orphaned files to remove (should be pre-screened by
                ``_find_orphaned_agents_files``).
            dry_run: If True, report what would be removed without deleting.

        Returns:
            List of cleanup status messages.
        """
        cleanup_messages = []

        if not orphaned_files:
            return cleanup_messages

        if dry_run:
            # In dry-run mode, just report what would be cleaned
            cleanup_messages.append(
                f"Would clean up {len(orphaned_files)} orphaned AGENTS.md files"
            )
            for file_path in orphaned_files:
                rel_path = portable_relpath(file_path, self.base_dir)
                cleanup_messages.append(f"  * {rel_path}")
        else:
            # Actually perform the cleanup
            cleanup_messages.append(f"Cleaning up {len(orphaned_files)} orphaned AGENTS.md files")
            removed_count = 0
            for file_path in orphaned_files:
                rel_path: str | None = None
                try:
                    rel_path = portable_relpath(file_path, self.base_dir)
                    # Defense-in-depth: re-check the marker before deleting.
                    # Read only a bounded prefix (same helper as _find_orphaned_agents_files).
                    if not self._file_has_apm_marker(file_path):
                        # _find_orphaned_agents_files already marker-gates, so
                        # this branch is unreachable in normal operation.  Emit
                        # at debug level only to avoid a stray user-facing
                        # warning (and the double-prefix it would get).
                        _logger.debug("Skipped %s: hand-authored file -- not removing", rel_path)
                        continue
                    file_path.unlink()
                    removed_count += 1
                    cleanup_messages.append(f"  + Removed {rel_path}")
                except Exception as e:
                    # rel_path is None if portable_relpath itself raised; fall back to
                    # the raw path so the error message is always informative.
                    display = rel_path if rel_path is not None else str(file_path)
                    cleanup_messages.append(f"  x Failed to remove {display}: {e!s}")
            if removed_count == 0:
                cleanup_messages.append("  [i] 0 files removed (all skipped)")

        return cleanup_messages

    def _validate_coverage(
        self,
        placements: builtins.list,
        all_instructions: builtins.list,
    ) -> builtins.list:
        """Validate that all instructions are covered by placements.

        Args:
            placements (List[PlacementResult]): Generated placements.
            all_instructions (List[Instruction]): All available instructions.

        Returns:
            List[str]: List of coverage warnings.
        """
        warnings = []
        placed_instructions = builtins.set()

        for placement in placements:
            placed_instructions.update(str(inst.file_path) for inst in placement.instructions)

        all_instruction_paths = builtins.set(str(inst.file_path) for inst in all_instructions)

        missing_instructions = all_instruction_paths - placed_instructions
        if missing_instructions:
            warnings.append(
                f"Instructions not placed in any AGENTS.md: {', '.join(missing_instructions)}"
            )

        return warnings
