"""Main compilation orchestration for AGENTS.md generation.

Timestamp generation removed in favor of deterministic Build ID handled after
full content assembly. This keeps repeated compiles byte-identical when source
primitives & constitution are unchanged.
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..core.target_detection import (
    CompileTargetType,
    can_dedup_agents_md_instructions,
    should_compile_agents_md,
    should_compile_claude_md,
    should_compile_gemini_md,
)
from ..primitives.discovery import discover_primitives
from ..primitives.models import PrimitiveCollection
from ..utils.path_security import (  # noqa: F401 -- patched by tests via agents_compiler namespace
    PathTraversalError,
    ensure_path_within,
)
from ..utils.paths import portable_relpath
from ..version import get_version
from ._agents_emit import _AgentsEmitMixin
from ._agents_output import _AgentsOutputMixin
from ._compiler_helpers import _detect_deployed_instructions as _detect_deployed_instructions
from ._compiler_helpers import compile_agents_md as compile_agents_md
from .constants import BUILD_ID_PLACEHOLDER  # noqa: F401 -- re-exported for consumers
from .link_resolver import resolve_markdown_links, validate_link_targets
from .template_builder import (
    TemplateData,
    build_conditional_sections,
    find_chatmode_by_name,
    generate_agents_md_template,
)

_logger = logging.getLogger(__name__)


# User-facing target aliases that map to the canonical "vscode" target.
# Kept in sync with target_detection.detect_target().
_VSCODE_TARGET_ALIASES = ("copilot", "agents")
_KNOWN_TARGETS = (  # noqa: RUF005
    "vscode",
    "claude",
    "cursor",
    "opencode",
    "codex",
    "agent-skills",
    "gemini",
    "antigravity",
    "windsurf",
    "kiro",
    "all",
    "minimal",
) + _VSCODE_TARGET_ALIASES
_COPILOT_ROOT_GENERATED_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"


# Compiler families allowed inside a multi-target frozenset (built by
# _resolve_compile_target() from CLI-validated target names). Kept narrow
# because the frozenset path bypasses _KNOWN_TARGETS validation.
_KNOWN_COMPILE_FAMILIES = frozenset({"agents", "vscode", "claude", "gemini"})


@dataclass
class CompilationConfig:
    """Configuration for AGENTS.md compilation."""

    output_path: str = "AGENTS.md"
    chatmode: str | None = None
    resolve_links: bool = True
    dry_run: bool = False
    with_constitution: bool = True  # Phase 0 feature flag

    # Multi-target compilation settings
    # "vscode" or "agents" -> AGENTS.md + .github/
    # "claude" -> CLAUDE.md + .claude/
    # "all" -> both targets
    # frozenset({"agents","claude"}) -> AGENTS.md + CLAUDE.md (multi-target)
    target: CompileTargetType = "all"

    # Distributed compilation settings (Task 7)
    strategy: str = "distributed"  # "distributed" or "single-file"
    single_agents: bool = False  # Force single-file mode
    trace: bool = False  # Show source attribution and conflicts
    local_only: bool = False  # Ignore dependencies, compile only local primitives
    debug: bool = False  # Show context optimizer analysis and metrics
    min_instructions_per_file: int = (
        1  # Minimum instructions per AGENTS.md file (Minimal Context Principle)
    )
    source_attribution: bool = (
        False  # Include source file comments (opt-in; default off to reduce token overhead)
    )
    clean_orphaned: bool = False  # Remove orphaned AGENTS.md files
    exclude: list[str] = None  # Glob patterns for directories to exclude during compilation

    # Deduplication opt-out (issue #1463): when True, instructions are always
    # included in CLAUDE.md regardless of .claude/rules/ contents.
    # Mirrors --no-dedup / --force-instructions CLI flag.
    no_dedup: bool = False

    # Managed-section mode (issue #1540): update only the APM-owned block
    # inside an existing AGENTS.md instead of overwriting the whole file.
    # Set compilation.agents_md.mode: managed_section in apm.yml to enable.
    agents_md_mode: str = "full"
    agents_md_start_marker: str = "<!-- apm:start -->"
    agents_md_end_marker: str = "<!-- apm:end -->"

    def __post_init__(self):
        """Handle CLI flag precedence after initialization."""
        if self.single_agents:
            self.strategy = "single-file"
        # Initialize exclude list if None
        if self.exclude is None:
            self.exclude = []
        _valid_modes = ("full", "managed_section")
        if self.agents_md_mode not in _valid_modes:
            raise ValueError(
                f"Unknown agents_md.mode {self.agents_md_mode!r}. "
                f"Supported values: {', '.join(repr(m) for m in _valid_modes)}."
            )

    @classmethod
    def from_apm_yml(cls, **overrides) -> "CompilationConfig":
        """Create configuration from apm.yml with command-line overrides.

        Args:
            **overrides: Command-line arguments that override config file values.

        Returns:
            CompilationConfig: Configuration with apm.yml values and overrides applied.
        """
        config = cls()

        # Try to load from apm.yml
        try:
            from pathlib import Path

            if Path("apm.yml").exists():
                from ..utils.yaml_io import load_yaml

                apm_config = load_yaml("apm.yml") or {}

                # Look for compilation section
                compilation_config = apm_config.get("compilation", {})

                # Apply config file values
                if "output" in compilation_config:
                    config.output_path = compilation_config["output"]
                if "chatmode" in compilation_config:
                    config.chatmode = compilation_config["chatmode"]
                if "resolve_links" in compilation_config:
                    config.resolve_links = compilation_config["resolve_links"]
                if "target" in compilation_config:
                    config.target = compilation_config["target"]

                # Distributed compilation settings (Task 7)
                if "strategy" in compilation_config:
                    config.strategy = compilation_config["strategy"]
                if "single_file" in compilation_config:
                    # Legacy config support - if single_file is True, override strategy
                    if compilation_config["single_file"]:
                        config.strategy = "single-file"
                        config.single_agents = True

                # Placement settings
                placement_config = compilation_config.get("placement", {})
                if "min_instructions_per_file" in placement_config:
                    config.min_instructions_per_file = placement_config["min_instructions_per_file"]

                # Source attribution
                if "source_attribution" in compilation_config:
                    config.source_attribution = compilation_config["source_attribution"]

                # Directory exclusion patterns
                if "exclude" in compilation_config:
                    exclude_patterns = compilation_config["exclude"]
                    if isinstance(exclude_patterns, list):
                        config.exclude = exclude_patterns
                    elif isinstance(exclude_patterns, str):
                        # Support single pattern as string
                        config.exclude = [exclude_patterns]

                # Managed-section mode (issue #1540)
                agents_md_config = compilation_config.get("agents_md", {})
                if "mode" in agents_md_config:
                    config.agents_md_mode = agents_md_config["mode"]
                if "start_marker" in agents_md_config:
                    config.agents_md_start_marker = agents_md_config["start_marker"]
                if "end_marker" in agents_md_config:
                    config.agents_md_end_marker = agents_md_config["end_marker"]

        except Exception as exc:
            _logger.debug("Config loading failed, using defaults: %s", exc)

        # Apply command-line overrides (highest priority)
        for key, value in overrides.items():
            if value is not None:  # Only override if explicitly provided
                setattr(config, key, value)

        # Handle CLI flag precedence
        if config.single_agents:
            config.strategy = "single-file"

        return config


@dataclass
class CompilationResult:
    """Result of AGENTS.md compilation."""

    success: bool
    output_path: str
    content: str
    warnings: list[str]
    errors: list[str]
    stats: dict[str, Any]
    has_critical_security: bool = False


class AgentsCompiler(_AgentsEmitMixin, _AgentsOutputMixin):
    """Main compiler for generating AGENTS.md files."""

    def __init__(self, base_dir: str = ".", source_dir: str | None = None):
        """Initialize the compiler.

        Args:
            base_dir (str): Base directory for compilation -- where AGENTS.md /
                CLAUDE.md outputs are written and the relative root for
                placement decisions.  Defaults to the current directory.
            source_dir (Optional[str]): Where primitives (``.apm/``,
                ``apm_modules/``) and source files are discovered.  Defaults to
                ``base_dir`` for back-compat; set explicitly when ``apm
                compile --root`` redirects writes but sources remain in
                ``$PWD``.
        """
        self.base_dir = Path(base_dir)
        self.source_dir = Path(source_dir) if source_dir else self.base_dir
        self.warnings: list[str] = []
        self.errors: list[str] = []
        self._logger = None

    def _log(self, method: str, message: str, **kwargs):
        """Delegate to logger if available, else no-op."""
        if self._logger:
            getattr(self._logger, method)(message, **kwargs)

    def compile(
        self,
        config: CompilationConfig,
        primitives: PrimitiveCollection | None = None,
        logger=None,
    ) -> CompilationResult:
        """Compile AGENTS.md and/or CLAUDE.md based on target configuration.

        Routes compilation to appropriate targets based on config.target:
        - "vscode" or "agents": Generate AGENTS.md + .github/ structure
        - "claude": Generate CLAUDE.md + .claude/ structure
        - "all": Generate both targets

        Args:
            config (CompilationConfig): Compilation configuration.
            primitives (Optional[PrimitiveCollection]): Primitives to use, or None to discover.

        Returns:
            CompilationResult: Result of the compilation.
        """
        self.warnings.clear()
        self.errors.clear()
        self._logger = logger

        try:
            # Use provided primitives or discover them (with dependency support)
            if primitives is None:
                if config.local_only:
                    # Use basic discovery for local-only mode
                    primitives = discover_primitives(
                        str(self.source_dir),
                        exclude_patterns=config.exclude,
                    )
                else:
                    # Use enhanced discovery with dependencies (Task 4 integration)
                    from ..primitives.discovery import discover_primitives_with_dependencies

                    primitives = discover_primitives_with_dependencies(
                        str(self.source_dir),
                        exclude_patterns=config.exclude,
                    )

            # Route to targets based on config.target.
            # Use target_detection helpers as the single source of truth so
            # new targets (codex, opencode, cursor, minimal, ...) route
            # correctly without touching this method again.
            if isinstance(config.target, frozenset):
                # Multi-target lists are normalized by _resolve_compile_target()
                # into compiler families only. Validate defensively for direct
                # API callers so invalid families do not silently produce
                # partial output or a successful no-op.
                invalid_families = config.target - _KNOWN_COMPILE_FAMILIES
                if invalid_families:
                    self.errors.append(
                        "Unknown compilation target family in multi-target set: "
                        f"{', '.join(sorted(invalid_families))}. "
                        "Expected subset of: "
                        f"{', '.join(sorted(_KNOWN_COMPILE_FAMILIES))}"
                    )
                    return CompilationResult(
                        success=False,
                        output_path="",
                        content="",
                        warnings=self.warnings.copy(),
                        errors=self.errors.copy(),
                        stats={},
                    )
                routing_target = config.target
            else:
                routing_target = (
                    "vscode" if config.target in _VSCODE_TARGET_ALIASES else config.target
                )

                if routing_target not in _KNOWN_TARGETS and config.target not in _KNOWN_TARGETS:
                    self.errors.append(
                        f"Unknown compilation target: {config.target!r}. "
                        f"Expected one of: {', '.join(sorted(set(_KNOWN_TARGETS)))}"
                    )
                    return CompilationResult(
                        success=False,
                        output_path="",
                        content="",
                        warnings=self.warnings.copy(),
                        errors=self.errors.copy(),
                        stats={},
                    )

            results: list[CompilationResult] = []

            if should_compile_agents_md(routing_target):
                results.append(self._compile_agents_md(config, primitives))

            if should_compile_claude_md(routing_target):
                results.append(self._compile_claude_md(config, primitives))

            if should_compile_gemini_md(routing_target):
                results.append(self._compile_gemini_md(config, primitives))

            # Some targets (e.g. cursor, agent-skills) use the data-driven
            # integration layer and don't need compilation.
            if not results:
                if logger and config.target == "agent-skills":
                    logger.progress(
                        "agent-skills -- no compile outputs, skipping",
                        symbol="info",
                    )
                return CompilationResult(
                    success=True,
                    output_path="",
                    content="",
                    warnings=self.warnings.copy(),
                    errors=self.errors.copy(),
                    stats={},
                )

            # Merge results from all targets
            return self._merge_results(results)

        except Exception as e:
            self.errors.append(f"Compilation failed: {e!s}")
            return CompilationResult(
                success=False,
                output_path="",
                content="",
                warnings=self.warnings.copy(),
                errors=self.errors.copy(),
                stats={},
            )

    def _compile_agents_md(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        """Compile AGENTS.md files (VSCode/Copilot target).

        Args:
            config (CompilationConfig): Compilation configuration.
            primitives (PrimitiveCollection): Primitives to compile.

        Returns:
            CompilationResult: Result of the AGENTS.md compilation.
        """
        # Handle distributed compilation (Task 7 - new default behavior)
        if config.strategy == "distributed" and not config.single_agents:
            result = self._compile_distributed(config, primitives)
        else:
            # Traditional single-file compilation (backward compatibility)
            result = self._compile_single_file(config, primitives)

        return self._maybe_emit_copilot_root_instructions(config, primitives, result)

    def _compile_distributed(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        """Compile using distributed AGENTS.md approach (Task 7).

        Args:
            config (CompilationConfig): Compilation configuration.
            primitives (PrimitiveCollection): Primitives to compile.

        Returns:
            CompilationResult: Result of distributed compilation.
        """
        from .distributed_compiler import DistributedAgentsCompiler

        errors = self.validate_primitives(primitives)
        self.errors.extend(errors)

        # Create distributed compiler with exclude patterns.  source_dir
        # carries through so primitive discovery + project-tree scoring
        # honor `apm compile --root` (sources stay in $PWD, writes
        # redirect to base_dir).
        distributed_compiler = DistributedAgentsCompiler(
            str(self.base_dir),
            exclude_patterns=config.exclude,
            source_dir=str(self.source_dir),
        )

        # Skip instructions in AGENTS.md when they are already deployed to
        # .github/instructions/ by `apm install` (avoids duplicate context for
        # Copilot, which reads both locations). Mirrors the .claude/rules/ check
        # on the Claude path (issue #1445); shared helper keeps the detection
        # logic in one place (R0801 guard).
        #
        # Target-aware: only dedup when EVERY AGENTS.md consumer also reads
        # .github/instructions/. Codex, OpenCode, Windsurf rely solely on
        # AGENTS.md for instructions, so dedup must not fire for those
        # targets (issue #1678).
        # --no-dedup / --force-instructions lets users opt out entirely.
        if config.no_dedup:
            skip_instructions = False
            self._log(
                "progress",
                "Including instructions in AGENTS.md (--no-dedup overrides deduplication)",
                symbol="info",
            )
        elif not can_dedup_agents_md_instructions(config.target):
            skip_instructions = False
        else:
            skip_instructions = _detect_deployed_instructions(
                self.base_dir / ".github" / "instructions",
                self.base_dir,
                lambda msg: self._log("warning", msg),
            )
            if skip_instructions:
                self._log(
                    "progress",
                    "Instructions already in .github/instructions/ -- omitting from"
                    " AGENTS.md to avoid duplicate context",
                    symbol="info",
                )

        # Prepare configuration for distributed compilation
        distributed_config = {
            "min_instructions_per_file": config.min_instructions_per_file,
            # max_depth removed - full project analysis
            "source_attribution": config.source_attribution,
            "debug": config.debug,
            "clean_orphaned": config.clean_orphaned,
            "dry_run": config.dry_run,
            "skip_instructions": skip_instructions,
            "with_constitution": config.with_constitution,
        }

        # Compile distributed
        distributed_result = distributed_compiler.compile_distributed(
            primitives, distributed_config
        )

        # Display professional compilation output (always show, not just in debug).
        # Guard: when ALL placements were suppressed (skip_instructions active and
        # content_map is empty), skip the placement-table formatter so the terminal
        # does not print "placing N files" immediately before "AGENTS.md not generated
        # (N files)" -- the two messages would be contradictory.  The INFO suppression
        # message below still fires unconditionally.
        # Mirrors the CLAUDE.md guard: `if compilation_results and not (skip_instructions
        # and files_written == 0)`.
        compilation_results = distributed_compiler.get_compilation_results_for_display(
            config.dry_run
        )
        if compilation_results and not distributed_result.all_suppressed:
            if config.debug or config.trace:
                # Verbose mode with mathematical analysis
                output = distributed_compiler.output_formatter.format_verbose(compilation_results)
            elif config.dry_run:
                # Dry run mode with placement preview
                output = distributed_compiler.output_formatter.format_dry_run(compilation_results)
            else:
                # Default mode with essential information
                output = distributed_compiler.output_formatter.format_default(compilation_results)

            # Display the professional output
            self._log("progress", output)

        if not distributed_result.success:
            self.warnings.extend(distributed_result.warnings)
            self.errors.extend(distributed_result.errors)
            return CompilationResult(
                success=False,
                output_path="",
                content="",
                warnings=self.warnings.copy(),
                errors=self.errors.copy(),
                stats=distributed_result.stats,
            )

        # Emit the user-visible INFO message for suppressed empty-shell placements.
        # Mirrors the CLAUDE.md analogue (agents_compiler.py:785-791).
        # This fires for both normal and dry-run modes so the user understands
        # why certain AGENTS.md files are absent.
        # Under partial suppression (some placements written, some suppressed) the
        # message clarifies that only the *suppressed* placements are absent so
        # users are not confused by the AGENTS.md files that *were* written.
        if distributed_result.suppressed_empty_paths:
            suppressed_count = len(distributed_result.suppressed_empty_paths)
            noun = "file" if suppressed_count == 1 else "files"
            if distributed_result.content_map:
                # Partial suppression: at least one AGENTS.md was written
                self._log(
                    "progress",
                    f"Skipped {suppressed_count} empty AGENTS.md {noun} -- "
                    ".github/instructions/ already covers Copilot; "
                    "pass --no-dedup to write all AGENTS.md files",
                    symbol="info",
                )
            else:
                # Full suppression: no AGENTS.md written at all
                self._log(
                    "progress",
                    f"AGENTS.md not generated ({suppressed_count} {noun}) -- "
                    ".github/instructions/ already covers Copilot; "
                    "pass --no-dedup to write AGENTS.md",
                    symbol="info",
                )

        # Handle dry-run mode (preview placement without writing files)
        if config.dry_run:
            # Count files that would be written (directories that exist)
            successful_writes = 0
            for agents_path in distributed_result.content_map.keys():  # noqa: SIM118
                if agents_path.parent.exists():
                    successful_writes += 1

            # Update stats with actual files that would be written
            if distributed_result.stats:
                distributed_result.stats["agents_files_generated"] = successful_writes

            # Don't write files in preview mode - output already shown above
            return CompilationResult(
                success=True,
                output_path="Preview mode - no files written",
                content=self._generate_placement_summary(distributed_result),
                warnings=self.warnings + distributed_result.warnings,
                errors=self.errors + distributed_result.errors,
                stats=distributed_result.stats,
            )

        # Write distributed AGENTS.md files
        successful_writes = 0
        total_content_entries = len(distributed_result.content_map)  # noqa: F841

        for agents_path, content in distributed_result.content_map.items():
            try:
                self._write_distributed_file(agents_path, content, config)
                successful_writes += 1
            except (OSError, ValueError) as e:
                self.errors.append(f"Failed to write {agents_path}: {e!s}")

        # Update stats with actual files written
        if distributed_result.stats:
            distributed_result.stats["agents_files_generated"] = successful_writes

        # Merge warnings and errors
        self.warnings.extend(distributed_result.warnings)
        self.errors.extend(distributed_result.errors)

        # Create summary for backward compatibility
        summary_content = self._generate_distributed_summary(distributed_result, config)

        return CompilationResult(
            success=len(self.errors) == 0,
            output_path=f"Distributed: {len(distributed_result.placements)} AGENTS.md files",
            content=summary_content,
            warnings=self.warnings.copy(),
            errors=self.errors.copy(),
            stats=distributed_result.stats,
        )

    def _compile_single_file(
        self, config: CompilationConfig, primitives: PrimitiveCollection
    ) -> CompilationResult:
        """Compile using traditional single-file approach (backward compatibility).

        Args:
            config (CompilationConfig): Compilation configuration.
            primitives (PrimitiveCollection): Primitives to compile.

        Returns:
            CompilationResult: Result of single-file compilation.
        """
        # Validate primitives
        validation_errors = self.validate_primitives(primitives)
        if validation_errors:
            self.errors.extend(validation_errors)

        # Generate template data
        template_data = self._generate_template_data(primitives, config)

        # Generate final output
        content = self.generate_output(template_data, config)

        # Write output file (constitution injection handled externally in CLI)
        output_path = str(self.base_dir / config.output_path)
        if not config.dry_run:
            self._write_output_file_with_config(output_path, content, config)

        # Compile statistics
        stats = self._compile_stats(primitives, template_data)

        return CompilationResult(
            success=len(self.errors) == 0,
            output_path=output_path,
            content=content,
            warnings=self.warnings.copy(),
            errors=self.errors.copy(),
            stats=stats,
        )

    def _merge_results(self, results: list[CompilationResult]) -> CompilationResult:
        """Merge multiple compilation results into a single result.

        Combines warnings, errors, stats, and content from multiple target
        compilations into a unified result.

        Args:
            results (List[CompilationResult]): List of compilation results to merge.

        Returns:
            CompilationResult: Merged compilation result.
        """
        if not results:
            return CompilationResult(
                success=True, output_path="", content="", warnings=[], errors=[], stats={}
            )

        if len(results) == 1:
            return results[0]

        # Merge all results
        merged_warnings: list[str] = []
        merged_errors: list[str] = []
        merged_stats: dict[str, Any] = {}
        output_paths: list[str] = []
        content_parts: list[str] = []

        for result in results:
            merged_warnings.extend(result.warnings)
            merged_errors.extend(result.errors)

            # Merge stats with prefixes to avoid collisions
            for key, value in result.stats.items():
                if key in merged_stats:
                    # Handle numeric stats by summing
                    if isinstance(value, (int, float)) and isinstance(
                        merged_stats[key], (int, float)
                    ):
                        merged_stats[key] = merged_stats[key] + value
                else:
                    merged_stats[key] = value

            if result.output_path:
                output_paths.append(result.output_path)
            if result.content:
                content_parts.append(result.content)

        # Determine overall success
        overall_success = all(r.success for r in results)

        return CompilationResult(
            success=overall_success,
            output_path=" | ".join(output_paths) if output_paths else "",
            content="\n\n---\n\n".join(content_parts) if content_parts else "",
            warnings=merged_warnings,
            errors=merged_errors,
            stats=merged_stats,
            has_critical_security=any(r.has_critical_security for r in results),
        )

    def validate_primitives(self, primitives: PrimitiveCollection) -> list[str]:
        """Validate primitives for compilation.

        Args:
            primitives (PrimitiveCollection): Collection of primitives to validate.

        Returns:
            List[str]: List of validation errors.
        """
        errors = []

        # Validate each primitive
        for primitive in primitives.all_primitives():
            primitive_errors = primitive.validate()
            if primitive_errors:
                # Source files live under source_dir; relativise display
                # paths against it so `apm compile --root` doesn't render
                # absolute or `../../` paths in warning messages.
                file_path = portable_relpath(primitive.file_path, self.source_dir)

                for error in primitive_errors:
                    # Treat validation errors as warnings instead of hard errors
                    # This allows compilation to continue with incomplete primitives
                    self.warnings.append(f"{file_path}: {error}")

            # Validate markdown links in each primitive's content using its own directory as base
            if hasattr(primitive, "content") and primitive.content:
                primitive_dir = primitive.file_path.parent
                link_errors = validate_link_targets(primitive.content, primitive_dir)
                if link_errors:
                    file_path = portable_relpath(primitive.file_path, self.source_dir)

                    for link_error in link_errors:
                        self.warnings.append(f"{file_path}: {link_error}")

        return errors

    def generate_output(self, template_data: TemplateData, config: CompilationConfig) -> str:
        """Generate the final AGENTS.md output.

        Args:
            template_data (TemplateData): Data for template generation.
            config (CompilationConfig): Compilation configuration.

        Returns:
            str: Generated AGENTS.md content.
        """
        content = generate_agents_md_template(template_data)

        # Resolve markdown links if enabled
        if config.resolve_links:
            content = resolve_markdown_links(content, self.base_dir)

        return content

    def _generate_template_data(
        self, primitives: PrimitiveCollection, config: CompilationConfig
    ) -> TemplateData:
        """Generate template data from primitives and configuration.

        Args:
            primitives (PrimitiveCollection): Discovered primitives.
            config (CompilationConfig): Compilation configuration.

        Returns:
            TemplateData: Template data for generation.
        """
        # Build instructions content.  source_dir keeps `<!-- Source: -->`
        # display paths relative to the user's working directory when
        # `apm compile --root` redirects writes elsewhere.
        instructions_content = build_conditional_sections(
            primitives.instructions, source_dir=self.source_dir
        )

        # Metadata (version only; timestamp intentionally omitted for determinism)
        version = get_version()

        # Handle chatmode content
        chatmode_content = None
        if config.chatmode:
            chatmode = find_chatmode_by_name(primitives.chatmodes, config.chatmode)
            if chatmode:
                chatmode_content = chatmode.content
            else:
                self.warnings.append(f"Chatmode '{config.chatmode}' not found")

        return TemplateData(
            instructions_content=instructions_content,
            version=version,
            chatmode_content=chatmode_content,
        )
