"""Shared constants for compilation extensions (constitution injection, etc.).

Also contains shared markers for build metadata stabilization. We intentionally
avoid timestamps in generated artifacts to guarantee byte-level idempotency; a
deterministic Build ID (content hash) is substituted post-generation.
"""

# Constitution injection markers
CONSTITUTION_MARKER_BEGIN = "<!-- SPEC-KIT CONSTITUTION: BEGIN -->"
CONSTITUTION_MARKER_END = "<!-- SPEC-KIT CONSTITUTION: END -->"
CONSTITUTION_RELATIVE_PATH = ".specify/memory/constitution.md"  # repo-root relative

# Build ID placeholder & regex pattern (line-level). The placeholder line is
# inserted during initial template generation; after all transformations
# (constitution injection, link resolution, etc.) we compute a SHA256 of the
# final content with this line removed and then replace it with the truncated
# hash. This ensures the hash is not self-referential and remains stable.
BUILD_ID_PLACEHOLDER = "<!-- Build ID: __BUILD_ID__ -->"

# Read-side ownership marker. Every root context file APM generates
# (CLAUDE.md, AGENTS.md, GEMINI.md, .github/copilot-instructions.md and the
# per-client variants) begins with a "<!-- Generated by APM CLI ... -->"
# line. The distinct target markers (CLAUDE_HEADER,
# AGENTS_MD_GENERATED_MARKER, the Copilot/Gemini variants) all share this
# prefix, so it is the single read-side signal for "did APM write this file?".
# The overwrite guard treats an existing target whose head lacks this prefix
# as hand-authored and refuses to clobber it silently.
APM_GENERATED_MARKER_PREFIX = "<!-- Generated by APM CLI"
