"""Security-conscious file I/O helpers for BaseIntegrator.

Extracted from :mod:`apm_cli.integration.base_integrator` to keep
that module under the 500-line ceiling while preserving all behaviour.

These helpers guard against TOCTOU races, symlink traversal, and
hardlink exploits when reading or discovering files within a package
root.  ``BaseIntegrator`` re-exports them as thin ``@staticmethod``
wrappers so all call-sites remain unchanged.
"""

from __future__ import annotations

import errno
import os
from pathlib import Path


class _SymlinkRaceError(OSError):
    """Raised by :func:`_read_bytes_no_follow` when the path becomes a
    symlink between the pre-check and the ``open()``.  Caught locally;
    never bubbles to callers."""


def _read_bytes_no_follow(path: Path) -> bytes:
    """Read *path* with ``O_NOFOLLOW`` semantics where supported.

    On POSIX, opens the file with ``os.O_NOFOLLOW`` so the kernel
    rejects the open atomically if the final path component is a
    symlink. This closes the TOCTOU race between
    ``Path.is_symlink()`` and ``Path.read_bytes()`` exploited by a
    co-tenant who can swap files for symlinks.

    On Windows (no ``O_NOFOLLOW``), falls back to a plain read; the
    caller's upfront ``is_symlink()`` check plus ``ensure_path_within``
    at the integrator call sites provide the containment guarantee.
    """
    flags = os.O_RDONLY | getattr(os, "O_BINARY", 0)
    nofollow = getattr(os, "O_NOFOLLOW", 0)
    flags |= nofollow
    try:
        fd = os.open(str(path), flags)
    except OSError as exc:
        # ELOOP is the canonical errno for "O_NOFOLLOW refused to open
        # a symlink"; some Linux kernels return EMLINK or ELOOP-equivalent.
        if nofollow and exc.errno in (errno.ELOOP, getattr(errno, "EMLINK", -1)):
            raise _SymlinkRaceError(exc.errno, f"Refused to follow symlink at {path}") from exc
        raise
    try:
        chunks: list[bytes] = []
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            chunks.append(chunk)
        return b"".join(chunks)
    finally:
        os.close(fd)


def is_content_identical_to_source(target_path: Path, source_path: Path) -> bool:
    """Return True if *target_path* is byte-identical to *source_path*.

    Used by non-skill integrators to silently *adopt* a pre-existing
    on-disk file that already matches what APM would deploy.

    Why this exists
    ---------------
    Without this short-circuit, the per-file loops in
    ``agent_integrator``, ``instruction_integrator``, ``prompt_integrator``
    and ``command_integrator`` would route the file straight into
    ``check_collision``. When the path is missing from ``managed_files``
    (e.g. lockfile was wiped, hand-edited, regenerated by an older APM
    build, or the user's previous install crashed before
    ``deployed_files`` was persisted) the file is treated as
    "user-authored", *skipped*, and never appended to ``target_paths``.

    That in turn leaves ``deployed_files`` empty in the new lockfile,
    which trips the ``required-packages-deployed`` policy check at the
    next install. Because ``policy_gate`` runs *before* ``integrate``
    in ``pipeline.py``, the install can never self-heal -- a permanent
    catch-22 lockout.

    ``skill_integrator`` already has an equivalent content-identity
    adopt at ``_promote_sub_skills`` (target.exists() +
    ``_dirs_equal``). This helper restores symmetry for non-skill
    primitives.

    Conservative by design
    ----------------------
    Only fires for *byte-identical* matches. Format-transforming
    targets (``codex_agent``, ``cursor_rules``, ``claude_rules``,
    ``windsurf_rules``, ``gemini_command``, ...) won't match -- they
    keep the existing skip behavior. This means we never silently
    adopt content that *might* have come from somewhere else; we only
    adopt files that are demonstrably the package's own bytes already
    on disk.

    TOCTOU hardening
    ----------------
    The classic ``is_symlink()`` -> ``read_bytes()`` sequence has a
    race window: a hostile co-tenant on the same machine could swap
    a regular file for a symlink between the two calls and cause
    ``read_bytes()`` to follow it to an attacker-controlled path,
    whose bytes might match source by construction. We close the
    race by reading through ``os.open(..., O_NOFOLLOW)`` so the
    kernel rejects the open atomically if the final component is a
    symlink. ``O_NOFOLLOW`` is a no-op constant on platforms that
    lack it (Windows), where the upfront ``is_symlink()`` check
    plus ``ensure_path_within`` at the call site provide adequate
    coverage (Windows also lacks the cheap unprivileged-symlink
    creation primitive that makes this race practical on POSIX).
    """
    try:
        if not target_path.exists() or not source_path.exists():
            return False
        # Cheap pre-check: reject obvious symlinks so we never even
        # attempt the open. Race-free verification follows below via
        # O_NOFOLLOW.
        if target_path.is_symlink() or source_path.is_symlink():
            return False
        try:
            target_bytes = _read_bytes_no_follow(target_path)
            source_bytes = _read_bytes_no_follow(source_path)
        except _SymlinkRaceError:
            # The path turned into a symlink between the pre-check
            # and the open() -- treat as non-identical so the caller
            # falls through to ``check_collision`` and the file is
            # NOT adopted. Silent (no diagnostic) because adopt is
            # an optimisation; the user-authored skip path is the
            # safe fallback.
            return False
        return target_bytes == source_bytes
    except OSError:
        return False


def _is_safe_glob_file(path: Path, package_path: Path) -> bool:
    """Return True when *path* is a regular in-package file safe to use."""
    if path.is_symlink():
        return False
    try:
        if path.stat().st_nlink > 1:
            return False
    except OSError:
        return False
    try:
        return path.resolve().is_relative_to(package_path.resolve())
    except (ValueError, OSError):
        return False


def find_files_by_glob(
    package_path: Path,
    pattern: str,
    subdirs: list[str] | None = None,
) -> list[Path]:
    """Search *package_path* (and optional subdirectories) for *pattern*.

    Symlinks and hardlinks are rejected outright to prevent traversal
    attacks.

    Args:
        package_path: Root of the installed package.
        pattern: Glob pattern (e.g. ``"*.prompt.md"``).
        subdirs: Extra subdirectory paths relative to *package_path*
                 to search (e.g. ``[".apm/prompts"]``).

    Returns:
        De-duplicated list of matching ``Path`` objects.
    """
    results: list[Path] = []
    seen: set = set()

    dirs = [package_path]
    if subdirs:
        dirs.extend(package_path / s for s in subdirs)

    for d in dirs:
        if not d.exists():
            continue
        for f in sorted(d.glob(pattern)):
            if not _is_safe_glob_file(f, package_path):
                continue
            resolved = f.resolve()
            if resolved not in seen:
                seen.add(resolved)
                results.append(f)

    return results
