"""Agent Plugins v1 contract helpers."""

from .assets import AssetInventoryError, open_verified_asset
from .constants import (
    AGENT_PLUGINS_SCHEMA_PREFIX,
    AGENT_PLUGINS_SITE_COMMIT,
    AGENT_PLUGINS_SPEC_COMMIT,
    AGENT_PLUGINS_SPEC_SHA256,
    AGENT_PLUGINS_VERSION,
    COM_MICROSOFT_APM_NAMESPACE,
    COM_MICROSOFT_APM_SCHEMA_VERSION,
    MAX_COMPONENT_ASSET_BYTES,
    MAX_COMPONENT_ASSET_ENTRIES,
    MCP_SCHEMA_ID,
    MCP_SCHEMA_SHA256,
    PLUGIN_SCHEMA_ID,
    PLUGIN_SCHEMA_SHA256,
    SUPPORTED_MCP_SCHEMA_IDS,
    SUPPORTED_PLUGIN_SCHEMA_IDS,
)
from .errors import (
    AgentPluginDeploymentBoundaryError,
    AgentPluginError,
    AgentPluginLegacyBoundaryError,
    AgentPluginManifestAuthorityError,
    AgentPluginManifestError,
    NotAgentPluginError,
    UnsupportedAgentPluginVersionError,
)
from .io import MAX_JSON_BYTES, read_json_document
from .ir import (
    AgentPlugin,
    AgentPluginAsset,
    AgentPluginComponents,
    AgentPluginDetection,
    AgentPluginDiagnostic,
    AgentPluginExecutable,
    AgentPluginIdentity,
    AgentPluginMcpServer,
    AgentPluginSkill,
    ApmConfiguration,
    ApmExtensionData,
    DiagnosticSeverity,
    FrozenJsonArray,
    FrozenJsonObject,
    FrozenJsonValue,
    JsonValue,
    McpServerType,
    SourceProvenance,
    thaw_frozen_json,
)
from .loader import (
    admit_legacy_plugin_manifest,
    detect_agent_plugin,
    load_agent_plugin,
    reject_agent_plugin_legacy_normalization,
)
from .validation import (
    ValidationResult,
    args_contain_literal_secret,
    contains_literal_secret_fields,
    is_agent_plugin_schema_id,
    schema_version_from_id,
    supports_mcp_schema_id,
    supports_plugin_schema_id,
    url_contains_literal_secret,
    validate_mcp_config_document,
    validate_mcp_config_file,
    validate_plugin_manifest_document,
    validate_plugin_manifest_file,
)


def __getattr__(name: str) -> object:
    """Lazily expose compatibility projection without a models import cycle."""
    if name != "project_agent_plugin_package":
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from .projection import project_agent_plugin_package

    return project_agent_plugin_package


__all__ = [
    "AGENT_PLUGINS_SCHEMA_PREFIX",
    "AGENT_PLUGINS_SITE_COMMIT",
    "AGENT_PLUGINS_SPEC_COMMIT",
    "AGENT_PLUGINS_SPEC_SHA256",
    "AGENT_PLUGINS_VERSION",
    "COM_MICROSOFT_APM_NAMESPACE",
    "COM_MICROSOFT_APM_SCHEMA_VERSION",
    "MAX_COMPONENT_ASSET_BYTES",
    "MAX_COMPONENT_ASSET_ENTRIES",
    "MAX_JSON_BYTES",
    "MCP_SCHEMA_ID",
    "MCP_SCHEMA_SHA256",
    "PLUGIN_SCHEMA_ID",
    "PLUGIN_SCHEMA_SHA256",
    "SUPPORTED_MCP_SCHEMA_IDS",
    "SUPPORTED_PLUGIN_SCHEMA_IDS",
    "AgentPlugin",
    "AgentPluginAsset",
    "AgentPluginComponents",
    "AgentPluginDeploymentBoundaryError",
    "AgentPluginDetection",
    "AgentPluginDiagnostic",
    "AgentPluginError",
    "AgentPluginExecutable",
    "AgentPluginIdentity",
    "AgentPluginLegacyBoundaryError",
    "AgentPluginManifestAuthorityError",
    "AgentPluginManifestError",
    "AgentPluginMcpServer",
    "AgentPluginSkill",
    "ApmConfiguration",
    "ApmExtensionData",
    "AssetInventoryError",
    "DiagnosticSeverity",
    "FrozenJsonArray",
    "FrozenJsonObject",
    "FrozenJsonValue",
    "JsonValue",
    "McpServerType",
    "NotAgentPluginError",
    "SourceProvenance",
    "UnsupportedAgentPluginVersionError",
    "ValidationResult",
    "admit_legacy_plugin_manifest",
    "args_contain_literal_secret",
    "contains_literal_secret_fields",
    "detect_agent_plugin",
    "is_agent_plugin_schema_id",
    "load_agent_plugin",
    "open_verified_asset",
    "project_agent_plugin_package",
    "read_json_document",
    "reject_agent_plugin_legacy_normalization",
    "schema_version_from_id",
    "supports_mcp_schema_id",
    "supports_plugin_schema_id",
    "thaw_frozen_json",
    "url_contains_literal_secret",
    "validate_mcp_config_document",
    "validate_mcp_config_file",
    "validate_plugin_manifest_document",
    "validate_plugin_manifest_file",
]
