"""Bootstrap the machine-readable requirements manifest from Appendix C.

One-time bootstrap. After this lands, the manifest at
docs/src/content/docs/specs/manifests/openapm-v0.1.requirements.yml is
maintained by the spec drafter on every edit and the orphan_check.py
gate enforces consistency against the spec body anchors.

Reads Appendix C of the OpenAPM v0.1 spec, emits a YAML manifest where
each entry carries id, keyword, section, conformance_class.

Run: uv run --extra dev python scripts/bootstrap_requirements.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "docs" / "src" / "content" / "docs" / "specs" / "openapm-v0.1.md"
MANIFEST_PATH = (
    REPO_ROOT
    / "docs"
    / "public"
    / "specs"
    / "manifests"
    / "openapm-v0.1.requirements.yml"
)

ROW_RE = re.compile(
    r"^\|\s*\[(req-[a-z]{2,3}-\d{3})\]\(#\1\)\s*\|\s*"
    r"(MUST NOT|SHOULD NOT|MUST|SHOULD|MAY)\s*\|\s*"
    r"([0-9.]+)\s*\|\s*"
    r"(producer|consumer|registry|governance)\s*\|\s*$"
)

ALLOWED_PREFIXES = {
    "mf",
    "ext",
    "lk",
    "pl",
    "rs",
    "pr",
    "tg",
    "sc",
    "rg",
    "cf",
}


def parse_appendix_c(spec_text: str) -> list[dict]:
    rows: list[dict] = []
    in_appendix_c = False
    for raw in spec_text.splitlines():
        if raw.startswith("## Appendix C"):
            in_appendix_c = True
            continue
        if in_appendix_c and raw.startswith("## Appendix D"):
            break
        if not in_appendix_c:
            continue
        m = ROW_RE.match(raw)
        if not m:
            continue
        req_id, keyword, section, klass = m.group(1), m.group(2), m.group(3), m.group(4)
        prefix = req_id.split("-")[1]
        if prefix not in ALLOWED_PREFIXES:
            raise ValueError(f"Unknown req prefix: {prefix} in {req_id}")
        rows.append(
            {
                "id": req_id,
                "keyword": keyword,
                "section": section,
                "conformance_class": klass,
            }
        )
    return rows


HEADER = """\
# OpenAPM v0.1 -- machine-readable requirements manifest.
#
# Generated initially by scripts/bootstrap_requirements.py from
# Appendix C of openapm-v0.1.md, then maintained by hand on every
# spec edit. The orphan_check.py CI gate enforces that this file
# stays a byte-for-byte projection of the HTML anchors in the spec
# body (the canonical source); Appendix C is a reader-aid derived
# from the same anchors.
#
# Do NOT edit this file alone. The three-step ritual for adding a
# normative requirement is:
#   1. Add the <a id="req-XXX"></a> anchor + prose to openapm-v0.1.md
#      and the corresponding Appendix C row.
#   2. Add the entry below.
#   3. Add or extend a test under tests/spec_conformance/ with
#      @pytest.mark.req("req-XXX") (and optionally cite a fixture
#      path).
# CI fails at any incomplete step.
#
# Ships in v0.1.1 informatively (see spec sec.12.6 reservation;
# v0.2 will promote the surrounding requirements to normative MUST).
"""


def emit_manifest(rows: list[dict]) -> str:
    lines: list[str] = [HEADER]
    lines.append("requirements_format_version: \"1\"")
    lines.append("spec_version: \"v0.1\"")
    lines.append("requirements:")
    for row in rows:
        lines.append(f"  - id: {row['id']}")
        lines.append(f"    keyword: {row['keyword']}")
        lines.append(f"    section: \"{row['section']}\"")
        lines.append(f"    conformance_class: {row['conformance_class']}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def main() -> int:
    spec_text = SPEC_PATH.read_text(encoding="utf-8")
    rows = parse_appendix_c(spec_text)
    if not rows:
        print("ERROR: parsed zero requirement rows from Appendix C", file=sys.stderr)
        return 1
    ids = [r["id"] for r in rows]
    if len(ids) != len(set(ids)):
        dupes = sorted({i for i in ids if ids.count(i) > 1})
        print(f"ERROR: duplicate ids in Appendix C: {dupes}", file=sys.stderr)
        return 1
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(emit_manifest(rows), encoding="ascii")
    print(f"wrote {MANIFEST_PATH.relative_to(REPO_ROOT)} ({len(rows)} requirements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
