#!/usr/bin/env python3
"""Enforce one canonical owner for generated-content footer wording."""

from __future__ import annotations

import ast
import sys
from pathlib import Path

_OWNER = Path("src/apm_cli/compilation/footer.py")
_CONSUMERS = (
    Path("src/apm_cli/compilation/agents_compiler.py"),
    Path("src/apm_cli/compilation/claude_formatter.py"),
    Path("src/apm_cli/compilation/distributed_compiler.py"),
    Path("src/apm_cli/compilation/template_builder.py"),
)
_OWNERSHIP_WORDING = "was generated by APM CLI. Do not edit manually."


def _string_constants(path: Path) -> list[str]:
    """Return string constants from a Python source file."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    return [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    ]


def find_violations(root: Path) -> list[str]:
    """Find duplicate footer wording or consumers bypassing the owner."""
    owner = root / _OWNER
    owner_tree = ast.parse(owner.read_text(encoding="utf-8"), filename=str(owner))
    owner_definitions = [
        node
        for node in owner_tree.body
        if isinstance(node, ast.FunctionDef) and node.name == "build_generation_footer"
    ]
    violations: list[str] = []
    if len(owner_definitions) != 1:
        violations.append(f"{_OWNER}: build_generation_footer must have exactly one definition")

    for relative_path in _CONSUMERS:
        consumer = root / relative_path
        source = consumer.read_text(encoding="utf-8")
        if "build_generation_footer(" not in source:
            violations.append(f"{relative_path}: generated footer must use build_generation_footer")

    compilation_root = root / "src/apm_cli/compilation"
    for source_path in compilation_root.rglob("*.py"):
        if source_path == owner:
            continue
        if any(_OWNERSHIP_WORDING in value for value in _string_constants(source_path)):
            relative_path = source_path.relative_to(root)
            violations.append(f"{relative_path}: footer ownership wording duplicates {_OWNER}")

    return violations


def main() -> int:
    """Run the generated-footer authority check."""
    root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).parents[1]
    violations = find_violations(root)
    if violations:
        print("[x] Generated footer wording must route through compilation/footer.py")
        for violation in violations:
            print(violation)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
