#!/usr/bin/env python3
"""
Generate npm packages for each platform and publish them.

This script:
1. Reads the version from pyproject.toml
2. Generates package.json for the main wrapper and platform packages using Jinja2 templates
3. Verifies the SHA-256 checksums of the inner executable generated by PyInstaller
4. Copies the compiled directory into each package directory in dist/npm/
5. Ready for npm publish
"""

import hashlib
import logging
import shutil
import sys
from collections import defaultdict
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

# Configure logging
logging.basicConfig(level=logging.INFO, format="[*] %(message)s")
logger = logging.getLogger(__name__)

# ==========================================
# CONSTANTS
# ==========================================

# Package & Binary naming
NPM_PACKAGE_PREFIX = "apm-cli"
BINARY_BASENAME = "apm"
BINARY_WINDOWS_EXT = ".exe"

# Platform configuration: (npm_platform, npm_arch)
PLATFORMS = [
    ("linux", "x64"),
    ("linux", "arm64"),
    ("darwin", "x64"),
    ("darwin", "arm64"),
    ("win32", "x64"),
]

# Mapping from npm names to APM release archive names
PLATFORM_MAP = {"linux": "linux", "darwin": "darwin", "win32": "windows"}
ARCH_MAP = {"x64": "x86_64", "arm64": "arm64"}

# File and Directory paths (relative to repo root)
MANIFEST_FILE = "pyproject.toml"
COMMON_FILES_TO_COPY = ["README.md", "LICENSE"]
TEMPLATES_DIR = "packages/@microsoft/apm-cli/templates"
DIST_DIR_NAME = "dist"
NPM_DIST_DIR_NAME = "npm"
BIN_DIR_NAME = "bin"

# Template filenames
TPL_PLATFORM_PACKAGE = "platform-package.json.jinja2"
TPL_MAIN_PACKAGE = "apm-cli-package.json.jinja2"
TPL_LAUNCHER = "apm-cli-bin.js.jinja2"

# ==========================================


def get_archive_name(npm_platform: str, npm_arch: str) -> str:
    """Convert npm platform/arch to APM release archive name."""
    return f"{BINARY_BASENAME}-{PLATFORM_MAP[npm_platform]}-{ARCH_MAP[npm_arch]}"


def get_repo_root() -> Path:
    return Path(__file__).parent.parent


def get_version(repo_root: Path) -> str:
    """Get the version from the manifest file."""
    import toml
    
    manifest_path = repo_root / MANIFEST_FILE
    with open(manifest_path, "r", encoding="utf-8") as f:
        data = toml.load(f)
        
    return data["project"]["version"]


def setup_jinja_env(repo_root: Path) -> Environment:
    template_dir = repo_root / TEMPLATES_DIR
    return Environment(loader=FileSystemLoader(str(template_dir)))


def copy_common_files(repo_root: Path, dest_dir: Path) -> None:
    """Copy common documentation and license files to the package directory."""
    for filename in COMMON_FILES_TO_COPY:
        src = repo_root / filename
        dest = dest_dir / filename
        if src.exists():
            shutil.copy2(src, dest)


def write_template(env: Environment, template_name: str, dest_path: Path, **kwargs) -> None:
    """Render a Jinja2 template and write to disk."""
    content = env.get_template(template_name).render(**kwargs)
    dest_path.write_text(content)
    logger.info(f"Writing {dest_path}")


def verify_binary_hash(binary_dir: Path, archive_name: str, npm_platform: str) -> None:
    """
    Verify the SHA256 hash of the target executable against the checksum file.
    """
    binary_name = f"{BINARY_BASENAME}{BINARY_WINDOWS_EXT}" if npm_platform == "win32" else BINARY_BASENAME
    binary_path = binary_dir / binary_name
    
    checksum_path = binary_dir.parent / f"{archive_name}.sha256"

    if not binary_path.exists():
        raise FileNotFoundError(f"Executable not found at: {binary_path}")
    if not checksum_path.exists():
        raise FileNotFoundError(f"Checksum file not found at: {checksum_path}")

    with open(checksum_path, "r", encoding="utf-8") as f:
        content = f.read().strip()
        if not content:
            raise ValueError(f"Checksum file is empty: {checksum_path}")
        expected_hash = content.split()[0].strip()

    sha256 = hashlib.sha256()
    with open(binary_path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            sha256.update(chunk)
    actual_hash = sha256.hexdigest()

    if expected_hash != actual_hash:
        raise ValueError(
            f"\nSECURITY ALERT: Hash mismatch for {archive_name}/{binary_name}!\n"
            f"Expected: {expected_hash}\n"
            f"Actual:   {actual_hash}\n"
            f"This indicates a corrupted download or an artifact substitution attack."
        )
    logger.info(f"Hash verified successfully: {actual_hash[:8]}... matches expected signature.")


def generate_platform_package(
    env: Environment, repo_root: Path, npm_dist_root: Path, npm_platform: str, npm_arch: str, version: str
) -> None:
    """Generate a single platform package into the distribution directory."""
    package_name = f"{NPM_PACKAGE_PREFIX}-{npm_platform}-{npm_arch}"
    package_root = npm_dist_root / package_name
    package_root.mkdir(parents=True, exist_ok=True)
    archive_name = get_archive_name(npm_platform, npm_arch)

    # 1. Write package.json
    write_template(
        env,
        TPL_PLATFORM_PACKAGE,
        package_root / "package.json",
        version=version,
        npm_platform=npm_platform,
        npm_arch=npm_arch,
    )

    # 2. Path to the unarchived binary folder
    binary_src = repo_root / DIST_DIR_NAME / archive_name
    if not binary_src.exists():
         raise FileNotFoundError(f"Binary directory not found at {binary_src}")
    
    # 3. Cryptographic Verification
    logger.info(f"Verifying hashes for {archive_name}...")
    verify_binary_hash(binary_src, archive_name, npm_platform)
    
    # 4. Copy binary content
    logger.info(f"Copying verified binary content from {binary_src} to {package_root}")
    shutil.copytree(binary_src, package_root, dirs_exist_ok=True)

    # 5. Copy standard files
    copy_common_files(repo_root, package_root)


def generate_main_package(env: Environment, repo_root: Path, npm_dist_root: Path, version: str) -> None:
    """Generate the main wrapper package with launcher and dependencies."""
    main_package_root = npm_dist_root / NPM_PACKAGE_PREFIX
    main_package_root.mkdir(parents=True, exist_ok=True)

    # 1. Write package.json
    write_template(
        env,
        TPL_MAIN_PACKAGE,
        main_package_root / "package.json",
        version=version,
        platforms=PLATFORMS,
    )

    # 2. Write launcher
    bin_dir = main_package_root / BIN_DIR_NAME
    bin_dir.mkdir(parents=True, exist_ok=True)
    
    grouped_platforms = defaultdict(list)
    for p_os, p_arch in PLATFORMS:
        grouped_platforms[p_os].append(p_arch)

    launcher_target = bin_dir / BINARY_BASENAME
    write_template(
        env,
        TPL_LAUNCHER,
        launcher_target,
        grouped_platforms=dict(grouped_platforms),
    )
    launcher_target.chmod(0o755)

    # 3. Copy standard files
    copy_common_files(repo_root, main_package_root)


def main() -> None:
    """Generate all npm packages."""
    logger.info("Starting npm package generation")

    repo_root = get_repo_root()
    npm_dist_root = repo_root / DIST_DIR_NAME / NPM_DIST_DIR_NAME
    version = get_version(repo_root)
    env = setup_jinja_env(repo_root)
    
    logger.info(f"Version: {version}")

    try:
        for npm_platform, npm_arch in PLATFORMS:
            logger.info(f"Generating package for {npm_platform}-{npm_arch}")
            generate_platform_package(env, repo_root, npm_dist_root, npm_platform, npm_arch, version)

        logger.info("Generating main package")
        generate_main_package(env, repo_root, npm_dist_root, version)
        
        logger.info("All packages generated successfully")
    except Exception as e:
        logger.error(f"Failed during package generation: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
