"""`apm compile` must not silently clobber a hand-authored root context file.

A repo that already ships a hand-written CLAUDE.md / AGENTS.md (no APM marker)
used to lose it on the first compile. Compile now refuses such an overwrite,
honours --force (with a .bak backup), and reports the collision under --dry-run.
"""

from pathlib import Path

import pytest
from click.testing import CliRunner

from apm_cli.cli import cli

_HAND_CLAUDE = "# My CLAUDE.md\n\nProject: Foo\n\nSkills precedence policy.\n"
_HAND_AGENTS = "# My AGENTS.md\n\nhand-authored content\n"


def _make_project(root: Path, target: str) -> None:
    (root / "apm.yml").write_text(
        f"name: guard-test\nversion: 1.0.0\ntargets:\n  - {target}\n",
        encoding="utf-8",
    )
    instructions = root / ".apm" / "instructions"
    instructions.mkdir(parents=True)
    (instructions / "local.instructions.md").write_text(
        '---\ndescription: Local policy\napplyTo: "**"\n---\n# Policy\nBe concise.\n',
        encoding="utf-8",
    )


def test_refuses_to_overwrite_hand_authored_claude_md(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    _make_project(tmp_path, "claude")
    claude = tmp_path / "CLAUDE.md"
    claude.write_text(_HAND_CLAUDE, encoding="utf-8")

    result = CliRunner().invoke(cli, ["compile", "--target", "claude"])

    assert result.exit_code != 0, result.output
    assert claude.read_text(encoding="utf-8") == _HAND_CLAUDE  # untouched
    assert not (tmp_path / "CLAUDE.md.bak").exists()
    assert "was not generated by APM" in result.output
    assert "--force" in result.output


def test_recompile_of_apm_generated_claude_md_still_overwrites(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    _make_project(tmp_path, "claude")
    runner = CliRunner()

    first = runner.invoke(cli, ["compile", "--target", "claude"])
    claude = tmp_path / "CLAUDE.md"
    assert first.exit_code == 0, first.output
    assert claude.is_file()
    assert "Generated by APM CLI" in claude.read_text(encoding="utf-8")

    second = runner.invoke(cli, ["compile", "--target", "claude"])

    assert second.exit_code == 0, second.output
    assert "Generated by APM CLI" in claude.read_text(encoding="utf-8")


def test_force_overwrites_hand_authored_and_writes_bak(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    _make_project(tmp_path, "claude")
    claude = tmp_path / "CLAUDE.md"
    claude.write_text(_HAND_CLAUDE, encoding="utf-8")

    result = CliRunner().invoke(cli, ["compile", "--target", "claude", "--force"])

    assert result.exit_code == 0, result.output
    assert "Generated by APM CLI" in claude.read_text(encoding="utf-8")
    backup = tmp_path / "CLAUDE.md.bak"
    assert backup.read_text(encoding="utf-8") == _HAND_CLAUDE  # original preserved


def test_dry_run_reports_collision_without_writing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    _make_project(tmp_path, "claude")
    claude = tmp_path / "CLAUDE.md"
    claude.write_text(_HAND_CLAUDE, encoding="utf-8")

    result = CliRunner().invoke(cli, ["compile", "--target", "claude", "--dry-run"])

    assert claude.read_text(encoding="utf-8") == _HAND_CLAUDE  # never written
    assert "hand-authored" in result.output
    assert "refuse" in result.output


def test_refuses_to_overwrite_hand_authored_agents_md(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    _make_project(tmp_path, "codex")  # codex family emits AGENTS.md
    agents = tmp_path / "AGENTS.md"
    agents.write_text(_HAND_AGENTS, encoding="utf-8")

    result = CliRunner().invoke(cli, ["compile", "--target", "codex"])

    assert result.exit_code != 0, result.output
    assert agents.read_text(encoding="utf-8") == _HAND_AGENTS  # untouched


def test_force_is_rejected_with_global(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    _make_project(tmp_path, "claude")

    result = CliRunner().invoke(cli, ["compile", "--global", "--force"])

    assert result.exit_code != 0
    assert "--force" in result.output
