"""Unit tests for source_attribution parity on the AGENTS.md path (issue #2634).

`compilation.source_attribution` defaults to False and is documented as the way
to suppress the cosmetic, token-consuming compile annotations.  #1584 implemented
that for the CLAUDE.md path but left the distributed AGENTS.md path emitting the
`<!-- APM Version: ... -->` comment and the generated-by footer unconditionally.

Two lines must stay unconditional regardless of the flag:
  * AGENTS_MD_GENERATED_MARKER -- `_find_orphaned_agents_files` only deletes files
    bearing it, so dropping it would stop `apm compile --clean` cleaning orphans.
  * BUILD_ID_PLACEHOLDER -- normalized away by drift detection.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from apm_cli.compilation.agents_compiler import AgentsCompiler, CompilationConfig
from apm_cli.compilation.distributed_compiler import (
    AGENTS_MD_GENERATED_MARKER,
    DistributedAgentsCompiler,
    PlacementResult,
)
from apm_cli.integration.targets import KNOWN_TARGETS
from apm_cli.primitives.models import Instruction, PrimitiveCollection

VERSION_COMMENT = "<!-- APM Version:"
FOOTER_LINE = "This file was generated by APM CLI. Do not edit manually."
REGENERATE_LINE = "To regenerate:"

# Derived rather than hardcoded so a newly added AGENTS.md target is covered
# automatically instead of silently regressing.
AGENTS_TARGETS = sorted(
    name for name, profile in KNOWN_TARGETS.items() if profile.compile_family == "agents"
)


def _project(tmp_path: Path, target: str, source_attribution: bool) -> PrimitiveCollection:
    """Minimal APM project with one instruction, compiled for ``target``."""
    (tmp_path / "apm.yml").write_text(
        f"name: attribution-{target}\n"
        "version: 1.0.0\n"
        "targets:\n"
        f"  - {target}\n"
        "compilation:\n"
        f"  source_attribution: {str(source_attribution).lower()}\n",
        encoding="utf-8",
    )
    instr_dir = tmp_path / ".apm" / "instructions"
    instr_dir.mkdir(parents=True, exist_ok=True)
    (instr_dir / "style.instructions.md").write_text(
        "---\ndescription: Style rule\napplyTo: '**'\n---\n# Style\nUse type hints.\n",
        encoding="utf-8",
    )
    instruction = Instruction(
        name="style",
        file_path=instr_dir / "style.instructions.md",
        description="Style rule",
        apply_to="**",
        content="Use type hints.",
        author="test",
        source="local",
    )
    primitives = PrimitiveCollection()
    primitives.add_primitive(instruction)
    return primitives


def _compile(tmp_path: Path, target: str, source_attribution: bool) -> str:
    primitives = _project(tmp_path, target, source_attribution)
    compiler = AgentsCompiler(str(tmp_path))
    config = CompilationConfig(target=target, dry_run=False, source_attribution=source_attribution)
    result = compiler._compile_distributed(config, primitives)
    assert result.success, f"compile failed for {target}: {result.errors}"
    agents_md = tmp_path / "AGENTS.md"
    assert agents_md.exists(), f"AGENTS.md must be generated for target {target}"
    return agents_md.read_text(encoding="utf-8")


@pytest.mark.parametrize("target", AGENTS_TARGETS)
def test_source_attribution_false_suppresses_cosmetic_blocks(tmp_path: Path, target: str) -> None:
    """source_attribution: false must drop the version comment and the footer."""
    body = _compile(tmp_path, target, source_attribution=False)

    assert VERSION_COMMENT not in body, f"{target}: version comment not suppressed:\n{body}"
    assert FOOTER_LINE not in body, f"{target}: footer not suppressed:\n{body}"
    assert REGENERATE_LINE not in body, f"{target}: regenerate line not suppressed:\n{body}"


@pytest.mark.parametrize("target", AGENTS_TARGETS)
def test_load_bearing_lines_survive_suppression(tmp_path: Path, target: str) -> None:
    """The marker and build ID must stay: --clean and drift detection need them."""
    body = _compile(tmp_path, target, source_attribution=False)

    assert AGENTS_MD_GENERATED_MARKER in body, (
        f"{target}: generated marker dropped -- 'apm compile --clean' would stop "
        f"removing orphaned AGENTS.md files:\n{body}"
    )
    assert "<!-- Build ID:" in body, f"{target}: build ID dropped:\n{body}"


@pytest.mark.parametrize("target", AGENTS_TARGETS)
def test_source_attribution_true_restores_cosmetic_blocks(tmp_path: Path, target: str) -> None:
    """Opting in must still emit both blocks."""
    body = _compile(tmp_path, target, source_attribution=True)

    assert VERSION_COMMENT in body, f"{target}: version comment missing when opted in:\n{body}"
    assert FOOTER_LINE in body, f"{target}: footer missing when opted in:\n{body}"


def test_agents_targets_list_is_not_empty() -> None:
    """Guard the derivation: an empty list would make the suite vacuously green."""
    assert AGENTS_TARGETS, "no targets with compile_family == 'agents' were discovered"


class TestGenerateAgentsContentDirectly:
    """Unit-level coverage of the guard in _generate_agents_content."""

    @staticmethod
    def _placement(tmp_path: Path) -> PlacementResult:
        return PlacementResult(
            agents_path=tmp_path / "AGENTS.md",
            instructions=[],
            coverage_patterns=set(),
            source_attribution={},
        )

    def test_disabled_omits_version_and_footer(self, tmp_path: Path) -> None:
        compiler = DistributedAgentsCompiler(base_dir=str(tmp_path))
        content = compiler._generate_agents_content(
            self._placement(tmp_path), PrimitiveCollection(), source_attribution=False
        )

        assert VERSION_COMMENT not in content
        assert FOOTER_LINE not in content
        assert AGENTS_MD_GENERATED_MARKER in content

    def test_enabled_includes_version_and_footer(self, tmp_path: Path) -> None:
        compiler = DistributedAgentsCompiler(base_dir=str(tmp_path))
        content = compiler._generate_agents_content(
            self._placement(tmp_path), PrimitiveCollection(), source_attribution=True
        )

        assert VERSION_COMMENT in content
        assert FOOTER_LINE in content

    def test_default_preserves_existing_direct_call_contract(self, tmp_path: Path) -> None:
        """Direct callers that pass no flag keep the pre-#2634 output."""
        compiler = DistributedAgentsCompiler(base_dir=str(tmp_path))
        content = compiler._generate_agents_content(
            self._placement(tmp_path), PrimitiveCollection()
        )

        assert VERSION_COMMENT in content
        assert FOOTER_LINE in content
