"""APM package install pipeline and post-install summary helpers."""

import builtins
import sys

from apm_cli.constants import APM_YML_FILENAME, InstallMode
from apm_cli.install.errors import (
    AuthenticationError,
    FrozenInstallError,
    PolicyViolationError,
)
from apm_cli.install.insecure_policy import InsecureDependencyPolicyError


def _install_apm_packages(ctx, outcome):
    """Execute the APM + transitive MCP installation pipeline.

    Parses ``apm.yml``, installs APM dependencies, collects and installs
    transitive MCP servers, and handles lockfile updates.

    Args:
        ctx: :class:`InstallContext` with configuration and environment.
        outcome: ``_ValidationOutcome`` from package validation (may be
            ``None`` when no explicit packages were passed).

    Returns:
        Tuple of ``(apm_count, mcp_count, lsp_count, apm_diagnostics)``.
    """
    # RULE B: late import so @patch("apm_cli.commands.install.<x>") intercepts
    # calls to APMPackage, LockFile, _install_apm_dependencies, _maybe_rollback_manifest,
    # _rich_*, _check_insecure_dependencies, migrate_lockfile_if_needed,
    # get_lockfile_path, _project_has_root_primitives, APM_DEPS_AVAILABLE.
    import apm_cli.commands.install as _m

    logger = ctx.logger

    logger.resolution_start(
        to_install_count=len(ctx.only_packages or []) if ctx.packages else 0,
        lockfile_count=0,  # Refined later inside _install_apm_dependencies
    )

    # Parse apm.yml to get both APM and MCP dependencies
    try:
        apm_package = _m.APMPackage.from_apm_yml(ctx.manifest_path)
    except Exception as e:
        logger.error(f"Failed to parse {ctx.manifest_display}: {e}")
        sys.exit(1)

    logger.verbose_detail(
        f"Parsed {APM_YML_FILENAME}: {len(apm_package.get_apm_dependencies())} APM deps, "
        f"{len(apm_package.get_mcp_dependencies())} MCP deps"
        + (
            f", {len(apm_package.get_dev_apm_dependencies())} dev deps"
            if apm_package.get_dev_apm_dependencies()
            else ""
        )
    )

    # Get APM and MCP dependencies
    apm_deps = apm_package.get_apm_dependencies()
    dev_apm_deps = apm_package.get_dev_apm_dependencies()
    has_any_apm_deps = bool(apm_deps) or bool(dev_apm_deps)
    mcp_deps = apm_package.get_mcp_dependencies()

    all_apm_deps = builtins.list(apm_deps) + builtins.list(dev_apm_deps)
    _m._check_insecure_dependencies(all_apm_deps, ctx.allow_insecure, logger)

    # Determine what to install based on install mode
    should_install_apm = ctx.install_mode != InstallMode.MCP
    should_install_mcp = ctx.install_mode != InstallMode.APM
    should_install_lsp = should_install_mcp

    # Show what will be installed if dry run
    if ctx.dry_run:
        # -- W2-dry-run (#827): policy preflight in preview mode --
        # Runs discovery + checks against direct manifest deps (not
        # resolved/transitive -- dry-run does not run the resolver).
        # Block-severity violations render as "Would be blocked by
        # policy" without raising.  Documented limitation: transitive
        # deps are NOT evaluated since the resolver does not run.
        from apm_cli.policy.install_preflight import run_policy_preflight as _dr_preflight

        _dr_preflight(
            project_root=ctx.project_root,
            apm_deps=builtins.list(apm_deps) + builtins.list(dev_apm_deps),
            mcp_deps=mcp_deps if should_install_mcp else None,
            no_policy=ctx.no_policy,
            logger=logger,
            dry_run=True,
        )

        from apm_cli.install.presentation.dry_run import render_and_exit

        render_and_exit(
            logger=logger,
            should_install_apm=should_install_apm,
            apm_deps=apm_deps,
            mcp_deps=mcp_deps,
            dev_apm_deps=dev_apm_deps,
            should_install_mcp=should_install_mcp,
            update=ctx.update,
            only_packages=ctx.only_packages,
            apm_dir=ctx.apm_dir,
        )
        return 0, 0, 0, None  # render_and_exit exits; this line is defensive

    # Install APM dependencies first (if requested)
    apm_count = 0

    # Migrate legacy apm.lock -> apm.lock.yaml if needed (one-time, transparent)
    _m.migrate_lockfile_if_needed(ctx.apm_dir)

    # Capture old MCP servers and configs from lockfile BEFORE
    # _install_apm_dependencies regenerates it (which drops the fields).
    # We always read this -- even when --only=apm -- so we can restore the
    # field after the lockfile is regenerated by the APM install step.
    old_mcp_servers: builtins.set = builtins.set()
    old_mcp_configs: builtins.dict = {}
    _lock_path = _m.get_lockfile_path(ctx.apm_dir)
    _existing_lock = _m.LockFile.read(_lock_path)
    if _existing_lock:
        old_mcp_servers = builtins.set(_existing_lock.mcp_servers)
        old_mcp_configs = builtins.dict(_existing_lock.mcp_configs)

    # Enter the APM install path when there are deps, local .apm/ primitives
    # (#714), OR orphan deps in the lockfile to clean up (manifest emptied).
    from apm_cli.core.scope import InstallScope
    from apm_cli.core.scope import get_deploy_root as _get_deploy_root
    from apm_cli.deps.lockfile import _SELF_KEY as _LOCK_SELF_KEY

    _cli_project_root = _get_deploy_root(ctx.scope)
    _has_orphan_deps_in_lock = bool(
        _existing_lock
        and not has_any_apm_deps
        and any(k != _LOCK_SELF_KEY for k in _existing_lock.dependencies)
    )
    apm_diagnostics = None
    if should_install_apm and (
        has_any_apm_deps
        or _m._project_has_root_primitives(_cli_project_root)
        or _has_orphan_deps_in_lock
    ):
        if not _m.APM_DEPS_AVAILABLE:
            logger.error("APM dependency system not available")
            logger.progress(f"Import error: {_m._APM_IMPORT_ERROR}")
            sys.exit(1)

        try:
            # If specific packages were requested, only install those
            # Otherwise install all from apm.yml.
            # `only_packages` was computed above so the dry-run preview
            # and the actual install share one canonical list.
            install_result = _m._install_apm_dependencies(
                apm_package,
                ctx.update,
                ctx.verbose,
                ctx.only_packages,
                force=ctx.force,
                parallel_downloads=ctx.parallel_downloads,
                logger=logger,
                scope=ctx.scope,
                auth_resolver=ctx.auth_resolver,
                target=ctx.target,
                allow_insecure=ctx.allow_insecure,
                allow_insecure_hosts=ctx.allow_insecure_hosts,
                marketplace_provenance=(
                    outcome.marketplace_provenance if ctx.packages and outcome else None
                ),
                protocol_pref=ctx.protocol_pref,
                allow_protocol_fallback=ctx.allow_protocol_fallback,
                no_policy=ctx.no_policy,
                audit_override=ctx.audit_override,
                legacy_skill_paths=ctx.legacy_skill_paths,
                frozen=ctx.frozen,
                plan_callback=ctx.plan_callback,
                skill_subset=ctx.skill_subset,
                skill_subset_from_cli=ctx.skill_subset_from_cli,
                refresh=ctx.refresh,
            )
            apm_count = install_result.installed_count
            apm_diagnostics = install_result.diagnostics
        except InsecureDependencyPolicyError:
            _m._maybe_rollback_manifest(ctx.snapshot_manifest_path, ctx.manifest_snapshot, logger)
            sys.exit(1)
        except AuthenticationError as e:
            # #1015: render auth diagnostics on the DEFAULT path (not --verbose).
            _m._maybe_rollback_manifest(ctx.snapshot_manifest_path, ctx.manifest_snapshot, logger)
            _m._rich_error(str(e))
            if e.diagnostic_context:
                _m._rich_echo(e.diagnostic_context)
            _m._rich_info("Tip: run 'apm doctor' to diagnose auth and connectivity.", symbol="info")
            sys.exit(1)
        except FrozenInstallError as e:
            _m._maybe_rollback_manifest(ctx.snapshot_manifest_path, ctx.manifest_snapshot, logger)
            _m._rich_error(str(e))
            for reason in e.reasons:
                _m._rich_echo(reason)
            _m._rich_info(
                "Tip: run 'apm outdated' to see what changed, then 'apm update'.",
                symbol="info",
            )
            sys.exit(1)
        except Exception as e:
            _m._maybe_rollback_manifest(ctx.snapshot_manifest_path, ctx.manifest_snapshot, logger)
            # #832: surface PolicyViolationError verbatim (no double-nesting).
            msg = (
                str(e)
                if isinstance(e, PolicyViolationError)
                else f"Failed to install APM dependencies: {e}"
            )
            logger.error(msg)
            if not ctx.verbose:
                logger.progress("Run with --verbose for detailed diagnostics")
            sys.exit(1)
    elif should_install_apm and not has_any_apm_deps:
        logger.verbose_detail("No APM dependencies found in apm.yml")

    # When --update is used, package files on disk may have changed.
    # Clear the parse cache so transitive MCP collection reads fresh data.
    if ctx.update:
        from apm_cli.models.apm_package import clear_apm_yml_cache

        clear_apm_yml_cache()

    # Collect transitive MCP dependencies from resolved APM packages
    transitive_mcp = []
    from apm_cli.core.scope import get_modules_dir
    from apm_cli.integration.mcp_integrator import MCPIntegrator

    apm_modules_path = get_modules_dir(ctx.scope)
    if should_install_mcp and apm_modules_path.exists():
        lock_path = _m.get_lockfile_path(ctx.apm_dir)
        transitive_mcp = MCPIntegrator.collect_transitive(
            apm_modules_path,
            lock_path,
            ctx.trust_transitive_mcp,
            diagnostics=apm_diagnostics,
        )
        if transitive_mcp:
            logger.verbose_detail(f"Collected {len(transitive_mcp)} transitive MCP dependency(ies)")
            mcp_deps = MCPIntegrator.deduplicate(mcp_deps + transitive_mcp)

    # -- S1/S2 fix (#827-C2/C3): enforce policy on ALL MCP deps ----
    # The pipeline gate phase (policy_gate.py) checks direct APM deps
    # and direct MCP deps from apm.yml.  However, transitive MCP
    # servers (discovered via collect_transitive above) are only known
    # after APM packages are installed.  Run a second preflight
    # against the *merged* MCP set (direct + transitive) BEFORE
    # MCPIntegrator writes runtime configs.  On PolicyBlockError we
    # abort the MCP write but leave already-installed APM packages
    # in place (they were approved by the gate phase).
    if should_install_mcp and mcp_deps:
        from apm_cli.policy.install_preflight import (
            PolicyBlockError as _TransitivePBE,
        )
        from apm_cli.policy.install_preflight import (
            run_policy_preflight as _transitive_preflight,
        )

        try:
            _transitive_preflight(
                project_root=ctx.project_root,
                mcp_deps=mcp_deps,
                no_policy=ctx.no_policy,
                logger=logger,
                dry_run=False,
            )
        except _TransitivePBE:
            logger.error(
                "MCP server(s) blocked by org policy. "
                "APM packages remain installed; MCP configs were NOT written."
            )
            logger.render_summary()
            sys.exit(1)

    # Continue with MCP installation (existing logic)
    mcp_count = 0
    new_mcp_servers: builtins.set = builtins.set()
    # Forward only the targets-key the user actually declared so parse_targets_field
    # in the gate sees the same dict shape it sees from raw apm.yml. Including a
    # `targets: None` placeholder when the user wrote `target:` (singular) would
    # falsely trip the conflict-mutex check (see core.apm_yml.parse_targets_field).
    # This restores parity with `apm install` for users on the modern `targets:`
    # plural form -- without this, `targets:` was silently dropped at the call
    # site and the gate fell back to permissive directory detection (#1335).
    mcp_apm_config: dict = {"scripts": apm_package.scripts or {}}
    if apm_package.targets is not None:
        mcp_apm_config["targets"] = apm_package.targets
    elif apm_package.target is not None:
        mcp_apm_config["target"] = apm_package.target
    if should_install_mcp and mcp_deps:
        mcp_count = MCPIntegrator.install(
            mcp_deps,
            ctx.runtime,
            ctx.exclude,
            ctx.verbose,
            stored_mcp_configs=old_mcp_configs,
            apm_config=mcp_apm_config,
            project_root=ctx.project_root,
            user_scope=(ctx.scope is InstallScope.USER),
            explicit_target=ctx.target,
            diagnostics=apm_diagnostics,
            scope=ctx.scope,
        )
        new_mcp_servers = MCPIntegrator.get_server_names(mcp_deps)
        new_mcp_configs = MCPIntegrator.get_server_configs(mcp_deps)

        # Remove stale MCP servers that are no longer needed
        stale_servers = old_mcp_servers - new_mcp_servers
        if stale_servers:
            MCPIntegrator.remove_stale(
                stale_servers,
                ctx.runtime,
                ctx.exclude,
                project_root=ctx.project_root,
                user_scope=(ctx.scope is InstallScope.USER),
                scope=ctx.scope,
            )

        # Persist the new MCP server set and configs in the lockfile
        MCPIntegrator.update_lockfile(new_mcp_servers, _lock_path, mcp_configs=new_mcp_configs)
    elif should_install_mcp and not mcp_deps:
        # No MCP deps at all -- remove any old APM-managed servers
        if old_mcp_servers:
            MCPIntegrator.remove_stale(
                old_mcp_servers,
                ctx.runtime,
                ctx.exclude,
                project_root=ctx.project_root,
                user_scope=(ctx.scope is InstallScope.USER),
                scope=ctx.scope,
            )
            MCPIntegrator.update_lockfile(builtins.set(), _lock_path, mcp_configs={})
        logger.verbose_detail("No MCP dependencies found in apm.yml")
    elif not should_install_mcp and old_mcp_servers:
        # --only=apm: APM install regenerated the lockfile and dropped
        # mcp_servers.  Restore the previous set so it is not lost.
        MCPIntegrator.update_lockfile(old_mcp_servers, _lock_path, mcp_configs=old_mcp_configs)

    # -------------------------------------------------------------------------
    # LSP integration (extracted to install/lsp/integration.py)
    # -------------------------------------------------------------------------
    from apm_cli.install.lsp import LSPIntegrationContext, run_lsp_integration

    lsp_count = run_lsp_integration(
        apm_package=apm_package,
        apm_modules_path=apm_modules_path,
        lock_path=_lock_path,
        existing_lock=_existing_lock,
        project_root=ctx.project_root,
        logger=logger,
        diagnostics=apm_diagnostics,
        ctx=LSPIntegrationContext(
            user_scope=(ctx.scope is InstallScope.USER),
            should_install=should_install_lsp,
            target_context=(mcp_apm_config, ctx.target, ctx.scope),
        ),
    )

    # Local .apm/ content integration is now handled inside the
    # install pipeline (phases/integrate.py + phases/post_deps_local.py,
    # refactor F3).  The duplicate target resolution, integrator
    # initialization, and inline stale-cleanup block that lived here
    # have been removed.

    return apm_count, mcp_count, lsp_count, apm_diagnostics


def _post_install_summary(
    *, logger, apm_count, mcp_count, lsp_count=0, apm_diagnostics, force, elapsed_seconds=None
):
    """Thin shim forwarding to :func:`apm_cli.install.summary.render_post_install_summary`.

    Kept as a module-level alias so existing tests that
    ``@patch("apm_cli.commands.install._post_install_summary")`` continue
    to work after the extraction (microsoft/apm#1116, F5).
    """
    from apm_cli.install.summary import render_post_install_summary

    render_post_install_summary(
        logger=logger,
        apm_count=apm_count,
        mcp_count=mcp_count,
        lsp_count=lsp_count,
        apm_diagnostics=apm_diagnostics,
        force=force,
        elapsed_seconds=elapsed_seconds,
    )


def _install_apm_dependencies(  # noqa: PLR0913
    apm_package,
    update_refs: bool = False,
    verbose: bool = False,
    only_packages=None,
    force: bool = False,
    parallel_downloads: int = 4,
    logger=None,
    scope=None,
    auth_resolver=None,
    target=None,
    allow_insecure: bool = False,
    allow_insecure_hosts=(),
    marketplace_provenance=None,
    protocol_pref=None,
    allow_protocol_fallback=None,
    no_policy: bool = False,
    audit_override=None,
    skill_subset=None,
    skill_subset_from_cli: bool = False,
    legacy_skill_paths: bool = False,
    frozen: bool = False,
    plan_callback=None,
    refresh: bool = False,
    lockfile_only: bool = False,
):
    """Thin wrapper -- builds an :class:`InstallRequest` and delegates to
    :class:`apm_cli.install.service.InstallService`.

    Kept here so that ``@patch("apm_cli.commands.install._install_apm_dependencies")``
    continues to intercept calls from the Click handler.  The service
    itself is the typed Application Service entry point for any future
    programmatic callers.
    """
    # RULE B: access APM_DEPS_AVAILABLE via install module so patches are honoured.
    import apm_cli.commands.install as _m

    if not _m.APM_DEPS_AVAILABLE:
        raise RuntimeError("APM dependency system not available")

    from apm_cli.install.request import InstallRequest
    from apm_cli.install.service import InstallService

    request = InstallRequest(
        apm_package=apm_package,
        update_refs=update_refs,
        verbose=verbose,
        only_packages=only_packages,
        force=force,
        parallel_downloads=parallel_downloads,
        logger=logger,
        scope=scope,
        auth_resolver=auth_resolver,
        target=target,
        allow_insecure=allow_insecure,
        allow_insecure_hosts=allow_insecure_hosts,
        marketplace_provenance=marketplace_provenance,
        protocol_pref=protocol_pref,
        allow_protocol_fallback=allow_protocol_fallback,
        no_policy=no_policy,
        audit_override=audit_override,
        skill_subset=skill_subset,
        skill_subset_from_cli=skill_subset_from_cli,
        legacy_skill_paths=legacy_skill_paths,
        frozen=frozen,
        plan_callback=plan_callback,
        refresh=refresh,
        lockfile_only=lockfile_only,
    )
    return InstallService().run(request)
